Azure/azurehpc

apps/nwchem/readme.md
=> Corrected readme file.

examples/simple_hpc_pbs/config.json, examples/simple_hpc_pbs/readme.md, examples/simple_hpc_pbs_rgs/config.json, examples/simple_hpc_pbs_rgs/readme.md, examples/simple_hpc_pbs_tgx/config.json, examples/simple_hpc_pbs_tgx/readme.md
I have added a readme for simple_hpc_pbs and have updated the config files and readme so that they work as provided. The issue was that we had the config hard coded for HC44 and we were telling them to provision in SCUS where we don't have HC nodes yet.
=> Added and updated readme and config files for simple_hpc_pbs_*

examples/anf_full/readme.md
Corrected path to prerequisites
=> Correct path to prerequisites

apps/prolb/install_prolb.sh, apps/prolb/prolb.sh, apps/prolb/readme.md, apps/prolb/runtime_prolb.sh
Adding ProLB
[AB#7108](https://azurecat.visualstudio.com/1f98a2d2-5799-4534-825f-83ba55f0b8ab/_workitems/edit/7108)
=> Adding Prolb

apps/starccm/install_starccm.sh, apps/starccm/readme.md, apps/starccm/run_civil_ompi4.pbs, apps/starccm/scripts/add_reqs.sh
Added files and instructions to run starccm+
=> Add starccm+

apps/health_checks/readme.md
Added a readme.md with a link to the blog post "Health checks for HPC workloads"
=> Inital readme.md

apps/io500/build_io500.sh, apps/io500/io500.pbs, apps/io500/readme.md
The IO-500 I/O storage benchmark is a standard benchmark to measure and compare HPC Storage solutions.
- IO-500 installation script
- IO-500 pbs run script.
=> IO-500 HPC I/O storage benchmark

apps/starccm/install_starccm.sh, apps/starccm/readme.md, apps/starccm/run_case.pbs
Made some additional changes to support different versions and updated the run_case.pbs since it did not work as expected. Also updated the readme.md
=> Starccm touchup

examples/anf_full/config.json, examples/anf_full/readme.md, libexec/azhpc-build.sh
The previous checkin the user had to load an az extension. These changes require the latest az cli but user no longer needs to load an az extension
=> Anf full touchup

scripts/cc_install.sh, scripts/cyclecli_install.sh
solve cycle cli install when used as a local script
=> Fix cycledeployment

README.md, libexec/azhpc-build.sh
Add the following property in config.json
"low_priority": true
It defaults to false.
=> Added support for low pri in VMSS

examples/lustre_combined/config.json, examples/lustre_demo/config.json, examples/lustre_full/config.json, examples/manageddisk_lustre/config.json, scripts/lfsclient.sh, scripts/lfspkgs.sh
=> Updated lustre to use patchless server

scripts/nfsserver.sh
-Needed to build singularity images on compute nodes.
=> Added no_root_squash to nfs exports.

examples/simple_hpc_pbs/config.json, examples/simple_hpc_pbs_rgs/config.json
Added a variable for the compute instances so that we could easily update them in a pipeline
=> Js pipelines

apps/intersect/install_case_intersect_2018.2.sh, apps/intersect/install_full_intersect_2018.2.sh, apps/intersect/readme.md, apps/intersect/run_intersect_2018.2.sh
Added support for installing and running intersect on cyclecloud.
=> Intersect cyclecloud 

libexec/azhpc-build.sh
* added the capability to create peer networks.
* added the capability to use preexisting ANF storage
* fixed an issue when storage names contain a "-" in the name. jq throws and error.
* Added additional checks before creating resources
=> added fixes for ANF and to peer a network

apps/intersect/install_case_intersect_2018.2.sh, apps/intersect/install_full_intersect_2018.2.sh, examples/simple_hpc_pbs_vpn/config.json, examples/simple_hpc_pbs_vpn/readme.md, scripts/setup_vpn_client.sh
-Added scripts and config.json to set-up a vpn client (for licensing e.g intersect)
-Modified intersect scripts for clarity and for the intersect pipeline
=> Added vpn client support (for licensing e.g intersect)

libexec/azhpc-build.sh
-  Added the peering option "--allow-forwarded-traffic"
=> Corrected peering

examples/simple_hpc_pbs_ppg/config.json, examples/simple_hpc_pbs_ppg/readme.md, libexec/azhpc-build.sh
-Support proximity placement groups (ppg) for resource types (vn and vmss).
This will allow IaaS resources to be deployed in the same datacenter (reducing latency). e.g deploy luster/beegfs and compute nodes in the same datacenter (Best practices).
=> Support proximity placement groups

azurehpc-ui/src/AzurehpcApp.js, libexec/azhpc-build.sh
add private dns functionality for reversed lookups...
=> Private dns

apps/wrf/WRFV4.0-rsl-8digit.patch, apps/wrf/install_wps_mvapich2.sh, apps/wrf/install_wps_openmpi.sh, apps/wrf/install_wrf_mvapich2.sh, apps/wrf/install_wrf_openmpi.sh
-Needed to source spack environment before loading spack software.
=> wrf installation bug fix

apps/wrf/install_wps_mvapich2.sh, apps/wrf/install_wps_openmpi.sh, apps/wrf/run_wrf_openmpi.pbs
- Added packages (jasper-devel & libpng-devel)
-Corrected path to WRF installation.
=> Corrected wps installation

apps/wrf/install_wps_mvapich2.sh, apps/wrf/install_wps_openmpi.sh, apps/wrf/install_wrf_mvapich2.sh, apps/wrf/install_wrf_omp_mvapich2.sh, apps/wrf/install_wrf_omp_openmpi.sh, apps/wrf/install_wrf_openmpi.sh, apps/wrf/run_wrf_mvapich2.pbs, apps/wrf/run_wrf_openmpi.pbs
-Loaded mpi libraries with module instead of spack.
-Added hybrid parallel builds (openmp + mpi) of wrf.
=> WRF update

libexec/azhpc-build.sh
format of az netappfiles changed in version ~2.0.77; updating this to latest version
=> move creation-token to file-path and bump az to 2.0.78

apps/health_checks/run_ring_osu_bw_hpcx.pbs, apps/health_checks/run_ring_osu_bw_hpcx_pbs.sh, libexec/azhpc-build.sh
Fixed an issue with ANF CLI and updated the scripts to work with the latest CentOS HPC images
=> Health checks update

libexec/azhpc-build.sh
adding options for os disk size and storage types
=> Storage updates

scripts/create_raid0.sh, scripts/lfsclient.sh
The disk size limitation was from fdisk - using parted instead now
The lustre client install was failing
=> Larger disk sizes and fixed lustre client install

apps/spack/readme.md
-Minor corrections to spack readme.md
=> Corrected spack readme.

libexec/azhpc-build.sh, libexec/azhpc-connect.sh, libexec/azhpc-run.sh, libexec/azhpc-status.sh, libexec/azhpc-watch.sh, libexec/install_helper.sh
Adding option for "instances" with a VM.  This will create multiple VMs and postfixing a zero padded number starting from 1.
=> Updates to add multiple instances of a vm

libexec/azhpc-build.sh
=> Switched to using spot

apps/wrf/readme.md
- Updated the WRF readme file, added instructions to create WRF v4 input cases using WPS v4.
- Will refer to this in the blog post.
=> Add instruction to create WRF input case using WPS

scripts/pbsclient.sh, scripts/pbsserver.sh
add a new attribute named "pool_name" which contains the VMSS name of the nodes
=> allow multiple VMSS with PBS

libexec/azhpc-build.sh
ultradisk needs zone specification and caching disabled...
=> add support for ultradisk with zone

apps/namd/install_namd_openmpi.sh, apps/namd/readme.md, apps/namd/run_namd_openmpi.pbs
-Initial version of namd 2.13 (build from source code).
-Supports building smp version
-Experimental memopt version support.
-Contains PBS run script.
=> namd application

libexec/azhpc-build.sh
Add support for premium disk performance optimization (tag to try and keep attached disks and VM close to each other.)
=> Added support for disk performance optimization.

apps/spack/build_spack.sh, apps/spack/readme.md
-Added flexibility installing spack with or without a buildcache.
=> Added some flexibility installing spack

apps/spack/packages.yaml
Corrected error in spack packages.yaml file.
=> Corrected error in spack packages.yaml file.

apps/imb-mpi/allreduce.sh, apps/imb-mpi/ringpingpong.sh, apps/osu/osu_bw.sh
simplify HPCX options to match the last image update
=> update HPCX mpi options

pyazhpc/azutil.py
change deployment command as it is deprecated
=> update to az deployment group

install.sh, libexec/pyazhpc-build.sh, libexec/pyazhpc-connect.sh, libexec/pyazhpc-destroy.sh, libexec/pyazhpc-get.sh, libexec/pyazhpc-init.sh, libexec/pyazhpc-preprocess.sh, libexec/pyazhpc-run.sh, libexec/pyazhpc-scp.sh, libexec/pyazhpc-status.sh
add OS detection and use PYTHONPATH in the alias to launch the python version
=> Fix pypath

scripts/nfsserver.sh
=> fix issue when no block device is used

scripts/lfsclient.sh
Added flock mount option (Needed to fix error in reveal).
=> Added flock mount option to lustre.

pyazhpc/azhpc.py
=> check for pip before fqdn else use hostname

pyazhpc/arm.py
=> Stop creating vnet when using an exiting one

pyazhpc/azinstall.py
=> Only create mount script when ANF is present

examples/cycleserver/01-prereqs.json, examples/cycleserver/02-cycleserver.json, examples/cycleserver/03-cycle-cli.json, examples/cycleserver/readme.md, pyazhpc/azconfig.py, pyazhpc/azhpc.py, pyazhpc/azinstall.py, scripts/cc_install.sh, scripts/cc_nsg.sh, scripts/cc_prereqs.sh
No error message is generated and the caller should check the
return status
=> Updated read_value to default to None

pyazhpc/arm.py
Added support for Custom images.
=> Support custom image

README.md, config.json, pyazhpc/arm.py, pyazhpc/azhpc.py
- Full documentation on the configuration file
- Update the README with the new commands and new variable expansion capabilities
=> Documentation update

examples/lustre_combined/config.json, examples/lustre_full/config.json, examples/manageddisk_lustre/config.json, scripts/lfspkgs.sh
updates in config file for a better pipeline test coverage and consistency with new capabilities like sakey.
=> Lustre updates for pipeline

apps/spack/build_spack.sh
Added global option (g) to sed to allow multiple substitutions to occur on the same line.
=> Spack (Added global option to sed for multiple substitution.)

ci/scripts/check_mountpoints.sh, ci/templates/jobs/build.yml, examples/blobfuse/pipeline.yml, examples/blobfuse/readme.md, examples/blobfuse/test.yml, examples/glusterfs_ephemeral/pipeline.yml, examples/glusterfs_ephemeral/readme.md, examples/glusterfs_ephemeral/test.yml, examples/lustre_combined/pipeline.yml, examples/lustre_combined/readme.md
New wave of pipelines for :
- beeond
- glusterfs
- lustre_combined 
fix issue that avoid deleting resource groups
=> Azure pipelines - Wave2

examples/glusterfs_data_disks/config.json, examples/glusterfs_data_disks/readme.md
Added flusterfs deployment using managed data disks.
=> glusterfs managed data disks example.

examples/cycleserver/03-cycle-cli.json, examples/cycleserver/test.yml, pyazhpc/arm.py, pyazhpc/azutil.py
This will mean an additional az cli call per public ip
Fix for issue #213
=> Check for DNS name before adding to arm template

examples/cycleserver/pipeline.yml, examples/cycleserver/test.yml, pyazhpc/arm.py, pyazhpc/azconfig.py, pyazhpc/azhpc.py, pyazhpc/azutil.py, scripts/cyclecli_install.sh
- added new test with cycle server to check the DNS changes
- fix PIP renaming issues
- merge fix on testing is DNS exists
=> fix DNS and PIP

ci/build.sh, examples/activedirectory/linuxclient-config.json, examples/anf_full/NFS_ANF.json, examples/anf_full/config.json, examples/beegfs/config.json, examples/beegfs_data_disk/config.json, examples/beegfs_local_ssd/config.json, examples/beegfs_pools/config.json, examples/beeond/config.json, examples/glusterfs_data_disks/config.json, examples/glusterfs_ephemeral/config.json, examples/lustre_combined/config.json, examples/lustre_full/config.json, examples/lustre_manageddisk/config.json, examples/pbs_cgroup/config.json, examples/reveal_E2E/config.json, examples/simple_hpc_pbs/config.json, examples/simple_hpc_pbs_docker/config.json, examples/simple_hpc_pbs_peer_network/config.json, examples/simple_hpc_pbs_rgs/config.json, examples/simple_hpc_pbs_singularity/config.json, examples/simple_hpc_pbs_tgx/config.json, examples/simple_hpc_pbs_vpn/config.json, scripts/pbsclient.sh, scripts/pbsdownload.sh, scripts/pbsserver.sh, tutorials/cfd_workflow/config.json, tutorials/oil_and_gas_intersect/config.json, tutorials/oil_and_gas_opm/config.json
- Don't use sudo in scripts but instead use sudo in config files
- change download endpoint to the github one
=> Update PBS install scripts

examples/slurm_autoscale/config.json, examples/slurm_autoscale/scripts/slurmpartition.sh
retrieve nodes properties dynamically so it can be used to different SKU types.
need to be tested on more SKUs
=> Get dynamic properties of nodes

apps/imb-mpi/allreduce.sh, apps/imb-mpi/readme.md, apps/imb-mpi/ringpingpong.sh
Addressed issues in the imb-mpi scripts
=> Updated running imb-mpi tests

apps/ior/ior.sh
-Removed hard-coded paths (Used variable instead e.g SHARED_APP)
-Corrected mpi module version
-Removed -z IOR option
=> IOR corrections

examples/cc_beegfs/init.sh
=> cc_beegfs - Corrected shebang

examples/cycleserver/02-cycleserver.json, examples/cycleserver/pipeline.yml, examples/cycleserver/readme.md
- Just few changes/improvements to the existing cycleserver example documentation.
- Correct `tenandid` with `tenantid` in `02-cycleserver.json`.
=> Update cycleserver documentation

blocks/cycle-cli-jumpbox.json, blocks/cycle-cli-local.json, blocks/cycle-install-server-managed-identity.json, changelog.md, examples/cc_beegfs/pipeline.yml, examples/cycleserver/03-cycle-cli.json, examples/cycleserver/03-jb-cycle-cli.json, examples/cycleserver/readme.md, examples/cycleserver_msi/pipeline.yml, examples/cycleserver_msi/readme.md, examples/cycleserver_msi/test_matrix.json, examples/cycleserver_msi/variables.json, scripts/azhpc4cycle.sh, scripts/cc_install_managed_identity.sh, scripts/cyclecli_install.sh
Supporting CycleCloud 8 for :
- Installing in a managed Identity context
- Intalling CycleCLI
Building cluster with azhpc is broken because of a bug in the CC CLI.
=> Support for CycleCloud 8

scripts/healthchecks.json
Same as PR#313, other file.
Should have been just one PR.
=> Converting vmSize to lowercase. ref:PR#313

pyazhpc/arm.py
=> Added zone to the arm pip resource if used #317

scripts/lfspkgs.sh
This will stop it before umounting /dev/sdb
=> The latest centos 7.7 has swap by default

changelog.md, scripts/lfsclient.sh, scripts/lfsmaster.sh
Fix to work with kernel upgrade in HPC image
=> using the dkms lustre client

blocks/anf.json, examples/cc_anf/init.sh, examples/cc_anf/pbscycle.json, examples/cc_anf/readme.md, examples/cc_anf/slurmcycle.json, examples/cc_anf/variables.json
blocks and example for anf on CycleCloud; with dynamic anf naming based on uuid to protect for naming conflicts on anf.
=> cc_anf example

blocks/glusterfs-cluster.json, examples/cc_glusterfs/init.sh, examples/cc_glusterfs/init.yml, examples/cc_glusterfs/pbscycle.json, examples/cc_glusterfs/pipeline.yml, examples/cc_glusterfs/readme.md, examples/cc_glusterfs/scripts/glusterfs_pool.sh, examples/cc_glusterfs/scripts/glusterfs_pool_master.sh, examples/cc_glusterfs/slurmcycle.json, examples/cc_glusterfs/variables.json
The copy of glusterfs_pool.sh inside of azurehpc was not used as it would not function with what had to be done. 
Others can see if they can get this to work.
A copy of glusterfs_pool.sh along with glusterfs_pool_master.sh has been included here. Everything was tested out.
=> This is a working version of glusterfs with Cycle Cloud

examples/gpu_numa_mapping/scripts/gpu_numa_mapping.sh
Correct minor error in gpu_numa_mapping.sh script (echo statement),
=> gpu-mapping scipt minor correct in echo statement

apps/health_checks/run_ring_imb_bw.pbs, apps/health_checks/run_ring_osu_bw_hpcx.pbs
Added an additional IB check for non SR-IOV enabled VMs
=> Js health checks

README.md, changelog.md, config.json, pyazhpc/arm.py
Added option for single placement group in the config file
=> Option for VMSS single placement group and overprovisioning

pyazhpc/azinstall.py
I've noticed this causing issues for AzureHPC OnDemand today and it was causing some tests to fail for @JonShelley
=> Wait for sshd to start on all nodes before install

apps/spack/azure_blob.py
-Added function azure_delete_blob()
-Corrected azure_list_blob
Get correct index based on location of "build_cache".
=> Spack (Added azure_delete_blob and corrected azure_list_lob)

apps/fio/build_fio.sh, apps/fio/fio.pbs, apps/fio/readme.md
- Update fio to 3.22
-Corrected build script
-Added non-direct I/O tests
-Added flushing Linux buffer before I/O tests.
=> Update fio to 3.22

blocks/lustre-cluster.json, examples/cc_lustre/init.sh, examples/cc_lustre/pbscycle.json, examples/cc_lustre/readme.md, examples/cc_lustre/slurmcycle.json, examples/cc_lustre/variables.json
The cc_lustre deployment scripts based building blocks has bee in local branch and have been extensively tested. Have to be moved to the Master branch examples.
=> Move cc_lustre to examples

examples/slurm_autoscale/pipeline.yml, pyazhpc/azhpc.py
VMs were not being deleted if multiple resource types were suspending in one call (e.g. interactive0001,viz3d0001)
=> Slurm suspend fix

apps/spack/build_spack.sh, apps/spack/darshan-runtime_package.patch
-Added patch to spack darshan build package.py, which will allow it to build a non-mpi version of darshan.
(darshan now also supports I/O profiling of non-mpi codes).
=> Spack darshan

pyazhpc/azhpc.py
=> Catch BadRequest and Conflict deployment errors

apps/spack/readme.md
-Updated readme about spack python3 requirement.
=> spack python3 requirement

apps/spack/readme.md
-Corrected the instructions in readme file to build osu-micro-benchmark with Intel MPI.
=> Spack Readme correction

apps/darshan/ior_darshan.pbs
-Error in ior syntax (should be -r)
=> Correct Darshan  syntax error.

apps/quantum-espresso/install_quantum_espresso.sh, apps/quantum-espresso/readme.md, apps/quantum-espresso/run_quantum_espresso.pbs
-Add quantum espresso build and run scripts.
=> Quantum espresso

examples/slurm_autoscale/readme.md
Improved Slurm Autoscale documentation by adding scheduler configuration cluster utilization info.
=> Added Slurm cluster usage in README

README.md, config.json, examples/grafana/config.json, examples/grafana/readme.md, pyazhpc/arm.py, scripts/install-telegraf.sh, scripts/telegraf-default.conf
- add NSG for grafana in the config file options
- telegraf configuration file outside of the telegraf install script
- added global tags for vmsize and vmss name
=> Grafana NSG and telegraf configuration file externalized

scripts/install_linux_rdp.sh
-Some corrections/improvements to linux xrdp install script.
=> Corrected install_linux_rdp.sh

examples/grafana/config.json, scripts/install-telegraf.sh, scripts/telegraf-default.conf
Use hard coded telegraf.conf file so that previous config file works
=> use default telegraf.conf

examples/anf/pipeline.yml, examples/anf_full/pipeline.yml, examples/beegfs/pipeline.yml, examples/beegfs_data_disk/pipeline.yml, examples/beegfs_local_ssd/pipeline.yml, examples/beegfs_pools/pipeline.yml, examples/beeond/pipeline.yml, examples/blobfuse/pipeline.yml, examples/cc_anf/pipeline.yml, examples/cc_beegfs/pipeline.yml, examples/cc_glusterfs/pipeline.yml, examples/cycleserver/pipeline.yml, examples/cycleserver_msi/pipeline.yml, examples/glusterfs_data_disks/pipeline.yml, examples/glusterfs_ephemeral/pipeline.yml, examples/grafana/pipeline.yml, examples/image/pipeline.yml, examples/lustre_avset/pipeline.yml, examples/lustre_combined/pipeline.yml, examples/lustre_full/pipeline.yml, examples/lustre_manageddisk/pipeline.yml, examples/managed_identity/pipeline.yml, examples/nvidia/pipeline.yml, examples/nvidia/test_matrix.json, examples/simple_hpc_pbs/pipeline.yml, examples/simple_hpc_pbs_zfs/pipeline.yml, examples/slurm_autoscale/pipeline.yml, examples/theia/pipeline.yml, examples/ultrassd/pipeline.yml
- Added a group for common variables, defined at the AzureDevOps project level
- need to reformat how variables are defined in yml files due to the introduction of group variables
=> Global variables across pipelines

examples/zcentral_remote_boost_linux/scripts/restart_gdm.sh, scripts/reset_vm_passwd.sh
-Corrected restart_gdm.sh (was in wrong directory, could not find config.json).
=> Zcentral fix

examples/zcentral_remote_boost_linux/scripts/linux_zcentral_remote_boost.sh
-Updated HPE ZCentral Remote Boost to 2020.1.0
=> Update ZCentral Remote Boost to 2020.1.0

examples/zcentral_remote_boost_linux/readme.md
Added Note about disabling HP Velocity (in the receiver settings).
If its not disabled you will not be able to connect to the sender.
=> Updated Zcentral Readme (about disabling HP Velocity setting.)

apps/health_checks/run_ring_osu_bw.sh
-update compiler version.
-update mvapich2 version.
=> Updated run_ring_osu_bw.sh (health_checks)

apps/health_checks/run_ring_osu_bw_hpcx.pbs, apps/health_checks/run_ring_osu_bw_hpcx_pbs.sh
Updated the HPCX health checks to address an error that we are seeing on Ubuntu. Also, modified a path so that users can easily use the scripts without having to move directories around.
=> Js health check update

apps/health_checks/readme.md
-Added an important requirement running clusterkit (need a even number of hosts in the hostlist)
=> clusterkit readme update.

blocks/cycle-install-server-managed-identity.json, pyazhpc/arm.py, scripts/cyclecli_install.sh
=> Revert "support of cyclecloud 8 and add cyclecloud port 8443"

apps/health_checks/install_mlc.sh
-Added check for HB SKU's (Hugepages are not required for HC)
=> MLC (Added check for HB SKU's)

apps/ior/ior.sh
-Drop all Client caches before each I/O test.
=> IOR (Drop all client caches.)

apps/imb-mpi/ringpingpong.sh
- Add a third command argument (TYPE to select between default (**latency**) measurement and **bandwidth**)
=> imb-mpi1 (added bandwidth measurement support)

apps/spack/build_spack.sh, apps/spack/fetch_strategy_azure.patch, apps/spack/packages.yaml
-Updated spack to v0.16.0
-Updated buildcache azure blob integration to v0.16.0
-Updated packages.yaml syntax to new format in v0.16.0
=> Spack updated to v0.16.0

ci/build.sh, ci/tags.json, ci/tags_variables.json
add tags to the resource group created with :
- pipeline name
- job id
- build number
Closing #444
=> Tag resource group with pipeline context

pyazhpc/azinstall.py
added a 60s timeout on the rsync command
Closing #449
=> Fix rsync timeout

blocks/cycle-install-server-managed-identity.json, examples/cycleserver_msi/pipeline.yml, examples/cycleserver_msi/readme.md, examples/cycleserver_msi/test_matrix.json, examples/cycleserver_msi/variables.json, scripts/cyclecloud7_config.py
- deploy CC 79.x with the public marketplace image
- added pipeline to test this deployment
- created python2 script to configure CC
=> added support for CC 79x

apps/starccm/install_starccm.sh, apps/starccm/run_case.pbs, apps/starccm/run_case_hpcx.pbs, apps/starccm/scripts/add_reqs.sh
Updated version and a required package in the add_reqs.sh script
=> Js starccm

experimental/AccelNet_tuning/map_irq_to_numa.sh, experimental/AccelNet_tuning/readme.md
-Script to tune Accelerated networking on HB120_v2 and HB60
=> Accelerated networking tuning for HB120_v2 and HB60

apps/imb-mpi/allreduce.sh, apps/imb-mpi/parser_allreduce.sh, apps/imb-mpi/parser_ringpingpong.sh, apps/imb-mpi/ringpingpong.lsf, apps/imb-mpi/ringpingpong.sh, apps/linpack/build_hpl.sh, apps/linpack/single_hpl.sh, apps/osu/hpcx_coll.lsf, apps/osu/hpcx_ring_pt2pt.lsf, apps/osu/osu_bw.sh, apps/osu/parser_osu_bw.sh
change the module init path to use /etc/profile.d/modules.sh so when lmod is installed it will still work
=> fix module init path

scripts/install-nfsserver.sh, scripts/nfsclient.sh
=> fix NFSServer thread settings and failed on error

apps/spack/build_spack.sh, apps/spack/packages.yaml, apps/wrf/build_wps.sh, apps/wrf/build_wrf.sh, apps/wrf/env_wrf.sh, apps/wrf/example/01_get_data.sh, apps/wrf/example/02_geogrid.sh, apps/wrf/example/03_viz_geogrid.sh, apps/wrf/example/04_ungrib.sh, apps/wrf/example/05_run_wrf.pbs, apps/wrf/example/namelist.tpl.input, apps/wrf/example/namelist.tpl.wps, apps/wrf/run_wrf_openmpi.pbs, apps/wrf/test.yml, ci/build.sh
- upgraded versions in spack builds
- fix pipeline
- added example with real life data
=> Added more WRF example

experimental/EasyBuild/easybuild_install.sh, experimental/EasyBuild/lmod_install.sh, experimental/EasyBuild/readme.md
This is an initial effort to add support for EasyBuild+Lmod on Azure HPC E2E deployments.
=> Add EasyBuild+Lmod to experimental

apps/wrf/build_wrf.sh
-Corrected syntax errors
-Added hpcx support
=> Added hpcx support to WRF

experimental/check_app_pinning_tool/check_app_pinning.py, experimental/check_app_pinning_tool/readme.md
Tool that will allow you to check if your HPC Application processes/threads are mapped/pinned optimally.
- Show VM NUMA topology (NUMA, cores and GPU's)
- Show where HPC Applications process/threads are mapped/pinned
- Gives specific warning if HPC Application is not pinned correctly.
=> HPC Application process pinning checking tool

experimental/check_app_pinning_tool/check_app_pinning.py, experimental/check_app_pinning_tool/readme.md
-Added "Last core id", which is the last core id a process was running on.
=> Update app pinning tool

apps/specstorage2020/install_specstorage_2020.sh, apps/specstorage2020/readme.md
Install and configure SPEC Storage 2020.
=> SPEC Storage 2020

experimental/check_app_pinning_tool/check_app_pinning.py, experimental/check_app_pinning_tool/readme.md
-Added support for HBv3 l3cache mapping
Will get warning if mapping/pinning hybrid parallel app to multiple l3caches
-Added SKU name lookup
=> Added support for HBv3 L3cache mapping (check_app_pinning_tool)

experimental/check_app_pinning_tool/check_app_pinning.py, experimental/check_app_pinning_tool/readme.md
- Added support for generation of MPI pinning syntax for HB(v1, v2 & v3) and NDv4 virtual machines.
- OpenMPI/HPCX and Intel MPI supported
- Tool will flag with warnings for incorrect combinations of number of processes and number of threads per process.
=> Added support for generation of MPI pinning syntax (check_app_pinning tool)

experimental/check_app_pinning_tool/check_app_pinning.py, experimental/check_app_pinning_tool/readme.md
-Added support to print the NUMA topology only (pass no args).
-Some minor corrections/edits in readme file.
=> Check_app_pinning_tool (Added support to print NUMA topology only (no args))

experimental/cvmfs_stack/README.md, experimental/cvmfs_stack/cvmfs_client_setup.sh, experimental/cvmfs_stack/cvmfs_repo_init.sh, experimental/cvmfs_stack/cvmfs_stratum0_install.sh
Add first iteration of scripts to automate CVMFS publisher, repository and client setup.
=> Add CVMFS repo init scripts

experimental/check_app_pinning_tool/check_app_pinning.py, experimental/check_app_pinning_tool/readme.md
-parse nvidia-smi (collect PIDs)
-Check for optimal PID to GPU id mapping.
=> (check_app_pinning) Added support to check for optimal PID to GPU id mapping.

README.md, blocks/lustre-cluster.json, examples/lustre_avset/config.json, examples/lustre_avset/readme.md, examples/lustre_combined/config.json, examples/lustre_combined/readme.md, examples/lustre_full/config.json, examples/lustre_full/readme.md, examples/lustre_ltop/config.json, examples/lustre_manageddisk/config.json, examples/lustre_manageddisk/readme.md, examples/lustre_marketplace/config.json, examples/lustre_marketplace/pipeline.yml, examples/lustre_marketplace/readme.md, examples/lustre_marketplace/test.yml, pyazhpc/arm.py, pyazhpc/azconfig.py, pyazhpc/azutil.py, scripts/lfshsm.sh, scripts/lfsimport.sh, scripts/lfsmaster.sh
* example for Lustre marketplace images.
* updated to latest HSM
* SAS key instead of storage key
* improved SAS support for duration (in addition to permissions)
* sensible concurrent HSM requests
=> Lustre marketplace

experimental/ndv4_a100_healthchecks/readme.md, experimental/ndv4_a100_healthchecks/report_dcgm.sh, experimental/ndv4_a100_healthchecks/run_bandwidthtest.sh, experimental/ndv4_a100_healthchecks/run_dcgm.sh, experimental/ndv4_a100_healthchecks/run_healthchecks.sh, experimental/ndv4_a100_healthchecks/run_nccl_all_reduce.sh, experimental/ndv4_a100_healthchecks/slurm_hosts_ips.py
-Added some Data Center GPU Manager(DCGM) healthchecks
-Added convenience script to print SLURM hostnames and corresponding IP addresses
-Reduced time to run NCCL ring test.
-Changed NCCL pinning
=> Ndv4 healthchecks update

experimental/gpu_monitoring/gpu_data_collector.py
- Get the physical host name and add it to the json that's pushed to Azure log analytics.
=> Added get_physicalhostname to GPU_Monitoring

experimental/check_app_pinning_tool/check_app_pinning.py, experimental/check_app_pinning_tool/readme.md
-Modified openmpi pinning syntax generated
-Added -nv arg to indicate how many VM are used in mpi communication.
-Print -np mpi option
-Change some variable names.
-updated readme file.
=> App Pinning tool (Modified openmpi pinning syntax)

experimental/AccelNet_tuning/map_irq_to_numa.sh, experimental/AccelNet_tuning/readme.md
- Added function to find the correct device corresponding to the Accelerated networking Virtual function.
- Updated readme
=> Updated AccelNet tuning script to support HBv3

experimental/cc_slurm_nhc/cc_slurm_nhc/specs/default/cluster-init/files/azure_gpu_app_clocks.nhc, experimental/cc_slurm_nhc/cc_slurm_nhc/specs/default/cluster-init/files/configure_nhc.sh, experimental/cc_slurm_nhc/cc_slurm_nhc/specs/default/cluster-init/files/nd96asr_v4.conf, experimental/cc_slurm_nhc/readme.md
- Added application GPU clock frequency check to see if maximum frequencies are set, it not it attempted to set them.
- Added section on what health checks are run in readme.
=> cc_slurm_nhc (Added application GPU clock frequency test.)

experimental/cc_slurm_nhc/cc_slurm_nhc/specs/default/cluster-init/files/configure_nhc.sh, experimental/cc_slurm_nhc/cc_slurm_nhc/specs/default/cluster-init/scripts/002_build_bandwidthtest.sh
Fixed miscellaneous code bugs.
=> cc_slurm_nhc bug fix

experimental/cc_slurm_nhc/cc_slurm_nhc/specs/default/cluster-init/files/azure_cuda_bandwidth.nhc, experimental/cc_slurm_nhc/cc_slurm_nhc/specs/default/cluster-init/files/azure_gpu_ecc.nhc, experimental/cc_slurm_nhc/cc_slurm_nhc/specs/default/cluster-init/files/configure_nhc.sh, experimental/cc_slurm_nhc/cc_slurm_nhc/specs/default/cluster-init/files/nd96asr_v4.conf, experimental/cc_slurm_nhc/readme.md
- Added GPU ECC error check 
- Minor changes to CUDA bandwidth test.
=> cc_slurm_nhc (Added GPU ECC error check)

experimental/cc_slurm_nhc/cc_slurm_nhc/specs/default/cluster-init/files/azure_gpu_persistence.nhc, experimental/cc_slurm_nhc/cc_slurm_nhc/specs/default/cluster-init/files/configure_nhc.sh, experimental/cc_slurm_nhc/cc_slurm_nhc/specs/default/cluster-init/files/nd96asr_v4.conf, experimental/cc_slurm_nhc/readme.md
-Added GPU persistence mode test.
=> cc_slurm_nhc (Added GPU persistence mode test)

experimental/cc_slurm_nhc/cc_slurm_nhc/specs/default/cluster-init/files/azure_gpu_app_clocks.nhc
-Remove hard-coded number of GPUs in azure_gpu_app_clocks.nhc
=> cc_slurm_nhc (remove hard-coded number of GPU's)

experimental/gpu_optimizations/max_gpu_app_clocks.sh, experimental/gpu_optimizations/readme.md
-Removed hard-coded number of GPUs in max_gpu_app_clocks.sh
=> GPU optimizations (Remove hard-coded number of GPUs)

experimental/cc_slurm_nhc/cc_slurm_nhc/specs/default/cluster-init/files/azure_ib_write_bw_gdr.nhc, experimental/cc_slurm_nhc/cc_slurm_nhc/specs/default/cluster-init/files/build_perftest_gdr.sh, experimental/cc_slurm_nhc/cc_slurm_nhc/specs/default/cluster-init/files/configure_nhc.sh, experimental/cc_slurm_nhc/cc_slurm_nhc/specs/default/cluster-init/files/nd96asr_v4.conf, experimental/cc_slurm_nhc/cc_slurm_nhc/specs/default/cluster-init/scripts/003_build_perftest_gdr.sh, experimental/cc_slurm_nhc/readme.md
-Added IB bandwidth performance test (ib_write_bw (GDR), for NDv4(A100))
=> cc_slurm_nhc (Added IB bandwidth performance test)

experimental/cc_beeond_ubuntu/cc_beeond_ubuntu/specs/default/cluster-init/files/README.txt, experimental/cc_beeond_ubuntu/cc_beeond_ubuntu/specs/default/cluster-init/files/beegfs-ondemand-stoplocal.patch, experimental/cc_beeond_ubuntu/cc_beeond_ubuntu/specs/default/cluster-init/files/beeond.patch, experimental/cc_beeond_ubuntu/cc_beeond_ubuntu/specs/default/cluster-init/files/setupbeeond_ubuntu.sh, experimental/cc_beeond_ubuntu/cc_beeond_ubuntu/specs/default/cluster-init/scripts/000_install_beeond.sh, experimental/cc_beeond_ubuntu/cc_beeond_ubuntu/specs/default/cluster-init/scripts/001_patch_beeond.sh, experimental/cc_beeond_ubuntu/cc_beeond_ubuntu/specs/default/cluster-init/scripts/002_patch_beegfs-ondemand-stoplocal.sh, experimental/cc_beeond_ubuntu/cc_beeond_ubuntu/specs/default/cluster-init/scripts/README.txt, experimental/cc_beeond_ubuntu/readme.md
-Support BeeOND 7.2.5 on Ubuntu-hpc (Tested on ubuntu-hpc 18.04+NDv4)
-Easily used by cyclecloud (cyclecloud project)
-Does not require/need copying ssh keys to root.
=> BeeOND support on ubuntu-hpc (Cyclecloud project)

README.md, ci/build.sh, ci/templates/steps/build-config.yml, pyazhpc/arm.py, pyazhpc/azhpc.py, pyazhpc/azinstall.py
This option will set the ssh port for VMs using a Public IP and set
the necessary NSG rule to allow access.
=> Added option for `ssh_port`

experimental/ndv4_a100_healthchecks/report_ib_write_lat.sh, experimental/ndv4_a100_healthchecks/run_ib_write_lat.sh, experimental/ndv4_a100_healthchecks/run_ib_write_lat_2N.sh, experimental/ndv4_a100_healthchecks/run_ring_ib_write_lat.sh
-Added a few IB latency tests for NDv4
=> NDv4 healthchecks (Added IB latency tests)

README.md, pyazhpc/arm.py, pyazhpc/azconfig.py
initial working setup of azure vpn gateway to get into a fully blocked subscription
=> adding azure vpn

experimental/cc_slurm_nhc/cc_slurm_nhc/specs/default/cluster-init/files/azure_nccl_allreduce_ib_loopback.nhc, experimental/cc_slurm_nhc/cc_slurm_nhc/specs/default/cluster-init/files/configure_nhc.sh, experimental/cc_slurm_nhc/cc_slurm_nhc/specs/default/cluster-init/files/nd96asr_v4.conf, experimental/cc_slurm_nhc/readme.md
Added NCCL allreduce IB loopback test
=> CC SLURM NHC (Add NCCL all-reduce IB loopback test)

experimental/ndv4_a100_healthchecks/get_physicalhostname.py
Added 
get_physicalhostname.py
cycleadmin@ip-0A2509BC:~$ ./get_physicalhostname.py
ip-0A2509BC physicalhostname = PHX801091908003
=> Add script to get physical host names. (to ndv4_a100_healthchecks)

experimental/gpu_monitoring/readme.md, experimental/gpu_monitoring/start_gpu_data_collector.sh, experimental/gpu_monitoring/stop_gpu_data_collector.sh
Corrected/updated 
- start_gpu_data_collector.sh
- stop_gpu_data_collector.sh
- readme
=> GPU monitoring update

experimental/ndv4_a100_healthchecks/readme.md, experimental/ndv4_a100_healthchecks/run_nccl_all_reduce.slrm, experimental/ndv4_a100_healthchecks/run_ring_nccl_allreduce_slurm.sh
-Added SLURM version of NCCL all-reduce ring pairs test. Multiple NCCL all-reduce pairs will run in parallel.
=> NDv4 healthchecks (SLURM version of NCCL all-reduce pairs ring test)

experimental/cc_slurm_nhc/cc_slurm_nhc/specs/default/cluster-init/files/azure_gpu_clock_throttling.nhc, experimental/cc_slurm_nhc/cc_slurm_nhc/specs/default/cluster-init/files/configure_nhc.sh, experimental/cc_slurm_nhc/cc_slurm_nhc/specs/default/cluster-init/files/nd96amsr_v4.conf, experimental/cc_slurm_nhc/cc_slurm_nhc/specs/default/cluster-init/files/nd96asr_v4.conf, experimental/cc_slurm_nhc/readme.md
Add test to check for GPU clock throttling (Issue warning, but do not DRAIN node)
=> CC_SLURM_NHC (Added test for GPU clock throttling)

experimental/cc_slurm_nhc/cc_slurm_nhc/specs/default/cluster-init/files/azure_gpu_ecc.nhc
=> cc_slurm_nhc (bug fix ECC check)

experimental/cc_slurm_nhc/cc_slurm_nhc/specs/default/cluster-init/files/azure_ib_link_flapping.nhc
=> CC_SLURM_NHC (Update IB link flapping test)

experimental/run_nccl_tests_ndv4/readme.md, experimental/run_nccl_tests_ndv4/run_nccl_tests.sh, experimental/run_nccl_tests_ndv4/run_nccl_tests_slurm.slrm
-Script to run NCCL tests optimally on NDv4 using MPI and hostfile.
-Script to run NCCL tests optimally on NDv4 using SLURM (sbatch/srun)
-Documentation.
=> Running NCCL tests optimally on NDv4

experimental/check_app_pinning_tool/check_app_pinning.py
- Find PID using a search pattern for the full command line (instead of just the executable name)
=> App pinning tool (Search for PID using full command line)

apps/health_checks/run_ring_osu_bw_hpcx.slurm, apps/health_checks/run_ring_osu_bw_hpcx_slurm.sh
Updated the scripts to run IB tests on Slurm WLM
=> Added support for IB tests for slurm

pyazhpc/arm.py
Update and correct network peering.
=> Update and correct network peering

README.md, pyazhpc/azconfig.py
Added support to retrieve the private IP of a VM.
e.g
ip.<RESOURCE_NAME>
=> Added support for private_ip macro

pyazhpc/arm.py
-Bug fix to correct ARM api version
=> Bug fix api version peering

experimental/deploy_cycle_slurm_ndv4/config.json
-Modified config.json (removed unneeded variables, removed NSG's and cycleserver PIP)
=> Updated deploy_cycle_slurm_ndv4

experimental/cc_slurm_nhc/cc_slurm_nhc/specs/default/cluster-init/files/configure_nhc.sh
- Changed the NHC timeout to 250
=> CC_SLURM_NHC( Changed NHC_TIMEOUT=250)

experimental/deploy_cycle_slurm_ndv4/config.json, experimental/deploy_cycle_slurm_ndv4/scripts/set_limits.sh, experimental/deploy_cycle_slurm_ndv4/slurm_cycle.txt
- Increase memory lock limits on login node.
=>   Cyclecloud slurm NDv4 (Modify limits on login node)

experimental/cc_slurm_nhc/cc_slurm_nhc/specs/default/cluster-init/files/configure_nhc.sh, experimental/cc_slurm_nhc/cc_slurm_nhc/specs/default/cluster-init/files/nd96amsr_v4.conf, experimental/cc_slurm_nhc/cc_slurm_nhc/specs/default/cluster-init/files/nd96asr_v4.conf
- Changed the ECC count threshold
- Changed the NHC run interval
=> CC_SLURM_NHC (change ECC threshold and NHC run interval)

experimental/check_app_pinning_tool/check_app_pinning.py, experimental/check_app_pinning_tool/readme.md
=> check_app_pinning tool (Added Mvapich2 support)

apps/starccm/run_case_hpcx.sbatch
Updated the run script for proper pinning on HB120rs_v3 and added a Slurm run script
=> updated run script and added a slurm run script

experimental/cc_slurm_nhc/cc_slurm_nhc/specs/default/cluster-init/files/nd96amsr_v4.conf, experimental/cc_slurm_nhc/cc_slurm_nhc/specs/default/cluster-init/files/nd96asr_v4.conf
- Changed CUDA BW test threshold to 20 GB/s.
=> CC_SLURM_NHC (Changed cuda_bw test threshold)

experimental/cc_slurm_pyxis_enroot/cc_slurm_pyxis_enroot/project.ini, experimental/cc_slurm_pyxis_enroot/cc_slurm_pyxis_enroot/specs/default/cluster-init/files/configure_pyxis.sh, experimental/cc_slurm_pyxis_enroot/cc_slurm_pyxis_enroot/specs/default/cluster-init/files/install_enroot.sh, experimental/cc_slurm_pyxis_enroot/cc_slurm_pyxis_enroot/specs/default/cluster-init/files/install_enroot_hooks.sh, experimental/cc_slurm_pyxis_enroot/cc_slurm_pyxis_enroot/specs/default/cluster-init/files/install_pyxis.sh, experimental/cc_slurm_pyxis_enroot/cc_slurm_pyxis_enroot/specs/default/cluster-init/files/prolog.sh, experimental/cc_slurm_pyxis_enroot/cc_slurm_pyxis_enroot/specs/default/cluster-init/files/slurmd_pmix.sh, experimental/cc_slurm_pyxis_enroot/cc_slurm_pyxis_enroot/specs/default/cluster-init/scripts/00_install_pyxis.sh, experimental/cc_slurm_pyxis_enroot/cc_slurm_pyxis_enroot/specs/default/cluster-init/scripts/01_configure_pyxis.sh, experimental/cc_slurm_pyxis_enroot/cc_slurm_pyxis_enroot/specs/default/cluster-init/scripts/02_install_enroot.sh, experimental/cc_slurm_pyxis_enroot/cc_slurm_pyxis_enroot/specs/default/cluster-init/scripts/03_install_enroot_hooks.sh, experimental/cc_slurm_pyxis_enroot/cc_slurm_pyxis_enroot/specs/default/cluster-init/scripts/04_slurmd_pmix.sh, experimental/cc_slurm_pyxis_enroot/readme.md
-Cyclecloud project to support containers via SLURM integrating Nvidia pyxis+enroot
=> cc_slurm_pyxis_enroot (SLURM container support via pyxis/enroot (cyclecloud project))

experimental/run_nccl_tests_ndv4/readme.md, experimental/run_nccl_tests_ndv4/run_nccl_tests_slurm_enroot.slrm
-Added script to run NCCL tests in a pytorch container using SLURM+pyxis+enroot
=> run_nccl_tests_ndv4 (Added slurm+pyxis+enroot NCCL test script)

experimental/cc_slurm_nhc/cc_slurm_nhc/specs/default/cluster-init/files/configure_nhc.sh, experimental/cc_slurm_nhc/cc_slurm_nhc/specs/default/cluster-init/files/epilog.sh, experimental/cc_slurm_nhc/cc_slurm_nhc/specs/default/cluster-init/files/kill_nhc.sh, experimental/cc_slurm_nhc/cc_slurm_nhc/specs/default/cluster-init/files/prolog.sh, experimental/cc_slurm_nhc/readme.md
-Added support to kill NHC via SLURM Prolog
=> CC_SLURM_NHC (Support killing NHC via SLURM Prolog)

experimental/cc_slurm_nhc/cc_slurm_nhc/specs/default/cluster-init/files/build_bandwidthtest.sh, experimental/cc_slurm_nhc/cc_slurm_nhc/specs/default/cluster-init/files/build_perftest_gdr.sh, experimental/cc_slurm_nhc/cc_slurm_nhc/specs/default/cluster-init/files/configure_nhc.sh, experimental/cc_slurm_nhc/cc_slurm_nhc/specs/default/cluster-init/files/install_nhc.sh, experimental/cc_slurm_nhc/readme.md
Bug fixes for SLURM prolog support (kill NHC before job starts)
=> cc slurm nhc (bug fix for prolog support)

experimental/cc_slurm_nhc/cc_slurm_nhc/specs/default/cluster-init/files/build_bandwidthtest.sh, experimental/cc_slurm_nhc/cc_slurm_nhc/specs/default/cluster-init/files/build_perftest_gdr.sh, experimental/cc_slurm_nhc/cc_slurm_nhc/specs/default/cluster-init/files/common_functions.sh, experimental/cc_slurm_nhc/cc_slurm_nhc/specs/default/cluster-init/files/configure_nhc.sh, experimental/cc_slurm_nhc/cc_slurm_nhc/specs/default/cluster-init/files/install_nhc.sh, experimental/cc_slurm_pyxis_enroot/cc_slurm_pyxis_enroot/specs/default/cluster-init/files/common_functions.sh, experimental/cc_slurm_pyxis_enroot/cc_slurm_pyxis_enroot/specs/default/cluster-init/files/configure_pyxis.sh, experimental/cc_slurm_pyxis_enroot/cc_slurm_pyxis_enroot/specs/default/cluster-init/files/install_enroot.sh, experimental/cc_slurm_pyxis_enroot/cc_slurm_pyxis_enroot/specs/default/cluster-init/files/install_enroot_hooks.sh, experimental/cc_slurm_pyxis_enroot/cc_slurm_pyxis_enroot/specs/default/cluster-init/files/install_pyxis.sh, experimental/cc_slurm_pyxis_enroot/cc_slurm_pyxis_enroot/specs/default/cluster-init/files/slurmd_pmix.sh
Improved code supportability through refactoring of is_slurm_controller function
=> Refactored is_slurm_controller function

experimental/deploy_cycle_slurm_ndv4/config.json, experimental/deploy_cycle_slurm_ndv4/config_pyxis_enroot.json, experimental/deploy_cycle_slurm_ndv4/readme.md
-Added a config file (config_pyxis_enroot.json) to do complete deployment including SLURM pyxis+enroot container support).
-Updated config.json
- Updated readme file
=> Deploy cycle slurm ndv4 (Added config file with pyxis+enroot)

experimental/gpu_monitoring/gpu_data_collector.py
Some bug fixes
-corrected syntax alignment
-corrected number of arguments in create_data_records function.
=> gpu_monitoring (bug fix, syntax alignment and number of arguments to function)

experimental/gpu_monitoring/gpu_data_collector.py
Bug fix in ethernet metrics
- Correct eth_counters dictionary key
=> GPU Monitoring (Bug fix, correct dictionary key.)

experimental/cc_slurm_nhc/cc_slurm_nhc/specs/default/cluster-init/files/azure_gpu_xid.nhc, experimental/cc_slurm_nhc/cc_slurm_nhc/specs/default/cluster-init/files/configure_nhc.sh, experimental/cc_slurm_nhc/cc_slurm_nhc/specs/default/cluster-init/files/nd96amsr_v4.conf, experimental/cc_slurm_nhc/cc_slurm_nhc/specs/default/cluster-init/files/nd96asr_v4.conf, experimental/cc_slurm_nhc/readme.md
- Added a test to check for GPU Xid errors.
=> CC_SLURM_NHC (Added check for GPU Xid errors)

experimental/check_gpu_ecc/check_gpu_ecc.py
- Modified the ECC error threshold (increased to 20M)
- Add SRAM ECC correctable ECC error threshold (10K)
=> check_gpu_ecc tool (Changed ECC error threshold and added a SRAM ECC error threshold)

experimental/cc_slurm_nhc/cc_slurm_nhc/specs/default/cluster-init/files/azure_cpu_drop_cache_mem.nhc, experimental/cc_slurm_nhc/cc_slurm_nhc/specs/default/cluster-init/files/azure_nccl_allreduce.nhc, experimental/cc_slurm_nhc/cc_slurm_nhc/specs/default/cluster-init/files/configure_nhc.sh, experimental/cc_slurm_nhc/cc_slurm_nhc/specs/default/cluster-init/files/nd96amsr_v4.conf, experimental/cc_slurm_nhc/cc_slurm_nhc/specs/default/cluster-init/files/nd96asr_v4.conf, experimental/cc_slurm_nhc/readme.md
- Added single node NCCL all-reduce test
- Bug fix applied to drop cache test.
- Increased NHC timeout value
- Changed order of tests in the config file, run drop cache test first.
=> cc slurm nhc (Added single node NCCL all-reduce test)

examples/zcentral_remote_boost_linux/scripts/linux_zcentral_remote_boost.sh, experimental/ndv4_a100_healthchecks/gen_hpcdiags.sh
Changed chmod 777 to chmod 775
=> fix some chmod security issues

experimental/gpu_monitoring/gpu_data_collector.py
=> gpu_monitoring (Bug fixes)

experimental/cc_slurm_nhc/cc_slurm_nhc/specs/default/cluster-init/files/install_nhc.sh
fixed what looks like a typo in the install_nhc.sh
=> bugfix in install_nhc

experimental/deploy_cycle_slurm_ndv4/config_pyxis_enroot.json, experimental/deploy_cycle_slurm_ndv4/config_pyxis_enroot_sacct_gpu_monitoring.json, experimental/deploy_cycle_slurm_ndv4/prereqs.json, experimental/deploy_cycle_slurm_ndv4/prereqs_sacct_la_ws.json, experimental/deploy_cycle_slurm_ndv4/readme.md, experimental/deploy_cycle_slurm_ndv4/scripts/cp_gpu_monitoring_scripts.sh, experimental/deploy_cycle_slurm_ndv4/scripts/create_log_analytics_ws.sh, experimental/deploy_cycle_slurm_ndv4/scripts/gpu_data_collector.sh, experimental/deploy_cycle_slurm_ndv4/scripts/gpu_monitoring_env.sh, experimental/deploy_cycle_slurm_ndv4/scripts/gpu_monitoring_start.sh
- Added support for GPU Monitoring (via Azure log analytics)
- Corrections in config files (NHC files)
=> Deploy_cycle_slurm_nhv4 (Added support for GPU monitoring (via Azure log analytics))

experimental/gpu_monitoring/gpu_data_collector.py, experimental/gpu_monitoring/readme.md
- Added cpu metrics (User, system, idle and iowait time, cpu loadavg)
- Added CPU memory (default:Total mem & free memory, many others can be monitored)
=> GPU Monitoring (Added CPU metrics)

experimental/gpu_monitoring/readme.md
1. Add disk_io log analytics/kusto image to readme file.
=> GPU Monitoring (Update readme, add disk_io image.)

README.md, pyazhpc/arm.py
update api version and change prefix to prefixes for nsg
and add rocky plan
=> Nsg multiple sourceip and rocky image plan

experimental/check_app_pinning_tool/check_app_pinning.py, experimental/check_app_pinning_tool/readme.md
- Added printing of the cpu mask (Hexadecimal taskset format) corresponding to each numa domain.
- 
e,g for NDv4
NumaNode id           Core ids      Mask                                                  GPU ids
============ ======== ====================== ==========
0                             ['0-23']           0xffffff                                                     [3, 2]
1                             ['24-47']         0xffffff000000                                         [1, 0]
2                             ['48-71']         0xffffff000000000000                             [7, 6]
3                             ['72-95']         0xffffff000000000000000000                 [5, 4]
=> App pinning tool (Added printing Numa mask)

experimental/hpc_monitoring/cc_hpc_monitoring/specs/default/cluster-init/files/hpc_data_collector.py, experimental/hpc_monitoring/readme.md
- Added support to monitor any scheduled events (e.g. Spot VM eviction, planned maintenance, service healing etc)
=> HPC/AI cluster monitoring (Support scheduled events)

experimental/cc_slurm_nhc/cc_slurm_nhc/specs/default/cluster-init/files/configure_nhc.sh, experimental/cc_slurm_nhc/cc_slurm_nhc/specs/default/cluster-init/files/run_nhc.sh, experimental/cc_slurm_nhc/cc_slurm_nhc/specs/default/cluster-init/files/wait_for_nhc.sh, experimental/hpc_monitoring/cc_hpc_monitoring/specs/default/cluster-init/files/hpc_data_collector.py, experimental/hpc_monitoring/readme.md
- Added support to collect filesystem inode metrics (-inodem option)
=> HPC monitor (Added support for filesystem inode monitoring)

experimental/check_app_pinning_tool/check_app_pinning.py, experimental/check_app_pinning_tool/readme.md
- Added support for LSF/bsub integration (using the LSF affinity syntax)
- Added new option -mt bsub
- LSF modification to enable LSF affinity on nodes
=> App pinning tool (Add LSF support)

experimental/cc_slurm_pyxis_enroot/cc_slurm_pyxis_enroot/specs/default/cluster-init/files/common_functions.sh, experimental/cc_slurm_pyxis_enroot/cc_slurm_pyxis_enroot/specs/default/cluster-init/files/configure_pyxis.sh, experimental/cc_slurm_pyxis_enroot/cc_slurm_pyxis_enroot/specs/default/cluster-init/files/install_enroot.sh, experimental/cc_slurm_pyxis_enroot/cc_slurm_pyxis_enroot/specs/default/cluster-init/files/install_pyxis.sh
- Update to Pyxis 0.16.1 and Enroot 3.4.1
- Ensure compatibility with CycleCloud v8.4+ and Ubuntu-HPC 22.4 images
=> Update Pyxis/Enroot CC project

experimental/aks_ndv4/azurehpc-health-checks.sh, experimental/aks_ndv5/nd96isr_h100_v5.conf
fix code due to upstream change:
https://github.com/Azure/azurehpc-health-checks
=> fix code for upsteam change

experimental/aks_npd_draino/draino/manifest.yml, experimental/aks_npd_draino/npd/Dockerfile, experimental/aks_npd_draino/npd/Makefile, experimental/aks_npd_draino/npd/deployment/node-problem-detector-config.yaml, experimental/aks_npd_draino/npd/deployment/node-problem-detector.yaml, experimental/aks_npd_draino/readme.md
- Added GPU VBIOS and GPU throttling tests to NPD+DRAINO (Used in AKS).
- Changed NPD base container image from pytorch to NGC CUDA.
=> Added GPU VBIOS and GPU throttling tests. (to AKS NPD+DRAINO)

experimental/hpc_monitoring/aks/Dockerfile, experimental/hpc_monitoring/aks/hpc-ai-monitor-config.yaml, experimental/hpc_monitoring/aks/hpc-ai-monitor.yaml, experimental/hpc_monitoring/aks/log_analytics_secret_key.yaml, experimental/hpc_monitoring/aks/readme.md
- Integration of hpc monitoring (monitor IB, GPU, network, disks and NFS) into AKS.
=>  Integration of hpc monitoring into AKS

experimental/hpc_monitoring/cc_hpc_monitoring/specs/default/cluster-init/files/hpc_data_collector.py
Added support to collect and monitor node metadata metrics (hostname, physical hostname and node resourceId).
Added new command line option (-node_metam  (--node_metadata_metrics), to enable this feature.
=> hpc monitoring (Added support to report node metadata metrics)

experimental/check_gpu_ecc/check_gpu_ecc.py, experimental/check_gpu_ecc/readme.md
Added support for retired pages.
- Check if greater than 62 retired pages
- Check if greater than 5 retired pages in 30 day period.
=> Added support for retired pages (check_gpu_ecc)
