Azure/azurehpc

apps/fio/build_fio.sh
apps/fio/fio.pbs
apps/fio/readme.md
apps/fio/windows_fio.ps1

-  Script to install fio from git repo.
- PBS script to run an fio throughput and IOPS benchmark on a single Linux client.
- Powershell script to run the same fio I/O benchmark (throughput and IOPS) on a windows client.

Fio single node benchmark test

---

libexec/install_helper.sh

Bubble up script errors when running either locally or remotely. The default behavior is to failed in case of any script returning exit code !=0

Bubble up errors when running scripts

---

libexec/common.sh
tests/test.json
tests/test_double_curly_brace.sh

You can use double curly braces anywhere in the value for it to be replace (and multiple are allowed, just not nested in the same string)

double curly brace for substitution in config

---

libexec/common.sh

It's unnecessary and often not the case where the RG for storage
is the same as the other resources.

Removed the RG from the command.

---

scripts/pbsclient.sh
scripts/pbsdownload.sh
scripts/pbsserver.sh
scripts/replace_nfs_with_anf.sh

The scripts would fail if they were run on compute nodes that had already been provisioned. These changes allow azhpc-build to be rerun on the compute nodes without having to delete everything and starting over.

Added fixes to azhpc-build for partially completed builds

---

examples/beegfs/config.json
examples/beegfs_data_disk/config.json
examples/beegfs_local_ssd/config.json
examples/beegfs_pools/config.json
scripts/beegfspkgs.sh

BeeGFS version 7.1.4 caused the azurehpc beegfs deployments to fail.
Selected the default beegfs repo to be 7.1.3.

Beegfs fix

---

scripts/lfsclient.sh
scripts/lfshsm.sh
scripts/lfsimport.sh

* client packages not needed for lustre 2.12 when server packages are installed
* only installing hsm packages if not already installed

Updated scripts for arm template version

---

libexec/azhpc-connect.sh

Removed the '-q' from the inner ssh to make it more obvious if the connect fails

Showing the errors in the azhpc-connect

---

apps/opm/flow_norne.sh

The HPC image must have changed to include gcc-9.2.0 and openmpi-4.0.2 rather than gcc-8.2.0 and openmpi-4.0.1 respectively. Need to load those modules now instead of the old.
{{{
[hpcuser@compute000000 ~]$ module av
---------------------------------------------------------------------------------------------------------------------------------------------------------------------- /usr/share/Modules/modulefiles ----------------------------------------------------------------------------------------------------------------------------------------------------------------------
dot                 gcc-9.2.0           module-git          module-info         modules             mpi/hpcx            mpi/hpcx-v2.5.0     mpi/impi            mpi/impi-2019       mpi/impi_2018.4.274 …

Update GCC and MPI modules

---

apps/spack/packages.yaml

Better to give specific version of libraries/compilers in spack config file packages.yaml. This will apply the special cases to only those specific versions (and not all versions).
These changes are also required so that namd can build correctly.

Provide specific versions in spack config file packages.yaml

---

scripts/cc_install.sh

Error deploying vanilla cyclecloud instance. 
{{{
Get cyclecloud_install.py
Run cyclecloud_install.py on cycleserver990507.southcentralus.cloudapp.azure.com
Creating temp directory /tmp/tmpH8Zc2H for installing CycleCloud
usage: cyclecloud_install.py [-h] [--azureSovereignCloud AZURESOVEREIGNCLOUD]
[--tenantId TENANTID]
[--applicationId APPLICATIONID]
[--applicationSecret APPLICATIONSECRET]
[--username USERNAME] [--hostname HOSTNAME]
[--acceptTerms] [--password PASSWORD]
[--storageAccount STORAGEACCOUNT]
cyclecloud_install.py: error: unrecognized arguments: --downloadURL https://cyclecloudarm.azureedge.net/cyclecloudrelease --cyclecloudVersion latest
Error : Error installing Cycle Cloud
}}}
Looks like the latest version of `cyclecloud_install.py` doesn't support the `downloadURL` and …

Remove `downloadURL` and `cyclecloudVersion` args

---

apps/namd/install_namd_openmpi.sh

-SKU_TYPE need to be defined before being used.
-CHARMARCH was set to the wrong value when NAMD_SMP was defined.

Corrected namd installation errors.

---

libexec/install_helper.sh
scripts/cc_install.sh

With this pull request cyclecloud can be installed without public-ip, the requirements for this
- A jumpBox with public-IP
- Setup private DNS (managed by az-hpc)
- a private network for Cycle VM
- Peering between cycle VNET and jumbox VNET (managed by az-hpc)

Add the possibility for cyclecloud to be installed without public-ip

---

scripts/beegfspkgs.sh

update to allow beegfs to install on CentOS-HPC 7.6 and 7.7

update to allow beegfs install on 7.6 and 7.7

---

changelog.md
examples/grafana/config.json
examples/grafana/readme.md
scripts/install-grafana.sh
scripts/install-telegraf.sh
scripts/telegraf_dashboard.json

Added Grafana and telegraf for monitoring resources
- installation scripts for grafana
- configure grafana database
- initialize InfluxDB datasoure
- import default dashboard
- installation script for telegraf (monitoring agent)

Added Grafana

---

pyazhpc/arm.py

The current os disk size default size of 32 GB does not work when deploying VM's running Windows servers (they require at least 128 GB).  (Currently, Windows deployments will fail (e.g examples/anf_cifs/ad-config.json))
This PR corrects an error deploying Windows VM's with the current os disk defaults (32 GB).
An os disk size default is not set, lets Azure select a suitable default. If a specific os disk size is required it can be set in the config file and inserted in the ARM template automatically.

Changed  os disk size default

---

examples/anf_cifs/ad-config.json

The python version currently does not support deploying without a jumpbox/headnode (The ad-config.json technically does not require a jumpbox because it only executes a local_script).
-Added a jumpbox (work-around)
-Changed post-install script to local_script  (Should we support post-install in the python version for backward compatibility?)

Corrected anf_cifs/ad-config.json

---

examples/pbs_cgroup/config.json
examples/pbs_cgroup/readme.md
scripts/pbs_cgroup.sh
scripts/pbs_restart.sh

-Added support for PBS cgroups
-Added example using PBS cgroups with ND40rs_v2 (divide resource into smaller units (e.g submit job on 2 gpus, 10 cpu cores and 160 GB of memory)

PBS cgroup support

---

pyazhpc/arm.py

Changed the default OS and data disk to Premium SSD's so there are no performance surprises when an NFS server or OS disk is created with default settings.

Changed os and data disk defaults to Premium SSD

---

examples/beegfs/config.json
examples/beegfs_data_disk/config.json
examples/beegfs_local_ssd/config.json
examples/beegfs_pools/config.json

The D3_v3 sku does not support premium disks. This sku was used as BeeGFS management node. This PR changes it to D4s_v3 (which supports premium disks).

Beegfs bug fix (due to change to premium disks)

---

scripts/beegfsc.sh
scripts/beegfspkgs.sh

-Changed default BeeGFS repo to be 7_1 (7_1.713 no longer exists)
-Resolved IB undefined symbols (Added IB include path, when building client)

Beegfs bug fix (Change default repo to be 7_1)

---

pyazhpc/azutil.py

I have had a number of deployment errors because generated saskey expired.
Would like to increase expiration to 2 hours.

Increased saskey expiration to 2 hours

---

scripts/make_filesystem.sh

Changed permission of mounted filesystem.
When using make_filesystem.sh to mount HB120rs_v2 nvme local ssh, I could not write because I did not have permission.

make_filesystem modification

---

examples/anf_cifs/ad-config.json
examples/anf_cifs/anf-config.json

The anf_cifs example is failing because we changed the default managed disk to be premium ssd, Needed to change the VM to one which supports premium disks.

Change VM to one which supports premium disks.

---

apps/wrf/install_wrf_intel.sh
apps/wrf/install_wrf_omp_intel.sh
apps/wrf/run_wrf_intel.pbs

Support build WRF V4.1.5 with Intel compilers and Intel MPI libraries.
-Tuned Intel compiler options.
-Significant performance improvements over GCC+OpenMPI version.

Support build WRF with intel compilers and Intel MPI libraries.

---

apps/spack/build_spack.sh
apps/spack/packages.yaml

Support Intel MPI (from CentOS-HPC 7.7 image) in spack.

Support Intel MPI in spack.

---

pyazhpc/azconfig.py

The container name is not extracted from string (e.g container/path/to/file) before calling azutil.get_storage_saskey. (In file azconfig.py)
Invalid saskey is generated.

Fix bug in generating storage account sas key

---

pyazhpc/azhpc.py

Symlinks are not followed anymore (to fix "trick" with the slurm example
where the scripts dir has a symlink to the yet-to-be-created ssh keys.

Symlinks copied in azhpc-init

---

examples/lustre_full/config.json
examples/lustre_manageddisk/config.json

add missing script that install jq on nodes. jq is needed by pbsclient.

fix missing jq

---

apps/wrf/install_wps_openmpi.sh

OpenMPI modulefile sets MPI_LIB to the location of the openmpi libraries.
WPS passes in that environmental variable directly (without -L) causing a build error.
WPS uses the mpi wrapper mpif90 to build and so it does not need the variable MPI_LIB because
the wrapper knows the location of the openmpi libraries and include files.
Fix is to unset MPI_LIB after the OpenMPI modulefile sets it (MPI_LIB="").

Fix WPS build error

---

scripts/cndefault.sh

The condition is true only if `epel-release` RPM  is already installed. Hence it never gets installed.
This fix has been tested by deploying `simple_hpc_pbs`.

Corrected epel-release installation condition

---

pyazhpc/arm.py

The default fault domain count is 5.
Large VMSS (300 HC instances in south central us) have failed to deploy when fault domain count is set to 5, but deploys correctly when set to 1.

Change fault domain count to be 1

---

scripts/node_healthchecks.sh

While allocating HBv2 from Batch the returned vmSize is `STANDARD_HB120rs_V2`, which generate a case mismatch in the check and gets, therefore, marked as "uncovered" (which should be probably changed to "unsupported").
Transforming everything into lowercase prevents this issue from arising.

Converting vmSize to lowercase.

---

scripts/install-telegraf.sh

Grafana default dashboard reports interrupts & contract but telegraf config didn't pushed those data to the InfluxDB so nothing to display from Grafana.

telegraf.conf modified to report interrupts and conntracks

---

examples/pbs_delete_idle_vmss/config.json
examples/pbs_delete_idle_vmss/readme.md
scripts/pbs_delete_idle_vmss.sh

The pbs_delete_idle_vmss.sh script generated a script, runs the script at regular intervals (default 10min, can be changed in the config.json) defined by the crontab.
- Runs on headnode (no ssh to compute instances, looks at the PBS resource "last_used_time" and job "status")
- When a PBS job has not run on the VMSS instance for the specified period. The instance will be removed from PBS and deleted.
- Will work with multiple VMSS's
- The instance idle time measurement only starts when a PBS job has completed on the instance. (i.e When the HPC cluster is first deployed the idle measurement does not start).
- A logfile (/tmp/azurehpc_delete_idle_vmss.log_$$) is generated to monitor/debug/record idle instances and what instances have been deleted.

PBS automatic deletion of idle vmss instances

---

README.md
changelog.md
examples/bastion/cloud-init.txt
examples/bastion/config_no_pub_ip.json
examples/bastion/readme.md
pyazhpc/arm.py
pyazhpc/azconfig.py

Added support for cloud-init in AzureHPC, primary use case would be install software on no-public IP VM/VMSS
(e.g AzureHPC prerequisites (git, jq, AzureHPC git clone, azcopy and azcli) (see cloud-init.txt example file).
Cloud-init scripts need to be uploaded to blob storage in advance of AzureHPC deployment.
The Cloud-init scripts can be then referenced using "cloud_init_sasurl" key.
e.g "cloud_init_sasurl": "sasurl.{{variables.storage_acc}}.data/cloud-init.txt"
The bastion config_no_pub_ip.json was extended to include cloud-init (Set-up AzureHPC prerequisites on no-pub IP jumpbox).

Added Cloud-init support in AzureHPC 

---

scripts/azhpc4cycle.sh

**Issue:**
The `azhpc4cycle.sh` script does not disable the jetpack converge when executed via cron. This causes the iptables rules blocking the metadata service to be re-instated few minutes after initial deployment.
**Cause:**
The `JETPACK_VERSION` variable is set to a null value when the script is executed via cron. This happens because cron processes are run in non-login shells, which do not source the content of `/etc/profile.d` where the path for the `jetpack` executable is set.
**Solution:**
Explicitly set the executable path when calling `jetpack`. 
Successfully tested on HPC node deployed in slurmcycle cluster.

Fix jetpack converge disable via cron

---

examples/gpu_numa_mapping/config.json
examples/gpu_numa_mapping/readme.md
examples/gpu_numa_mapping/scripts/bwtest_gpu_map.sh
examples/gpu_numa_mapping/scripts/gpu_numa_mapping.sh
examples/gpu_numa_mapping/scripts/gpu_topo.cpp

This calculates the correct ND40rs_v2 GPU mapping (topology and mapping to the correct numa domain).
I have complemented some existing scripts by adding a cuda bandwidthTest benchmark to determine the correct GPU mapping to host numa domain (or socket). The mapping file is written to /tmp/gpu_map_file  (e.g 3,4,5,6,7,2,1,0).
I also added a second gpu_mapping script called (bwtest_gpu_map.sh), this scripts used cuda bandwidthtest exclusively to determine the GPU mapping. It does a BW test from each GPU tp core 0-1 (Numa domain 0), then sorts the results and writes the mapping to /tmp/gpu_mapfile and the GPU BW results to /tmp/gpu_bwtest_file (good sanity check).

ND40rs v2 gpu numa mapping

---

scripts/beegfsc.sh

By default BeeGFS sets the client side caching mode to "buffered" (i.e small pool of resources set aside for caching, managed by BeeGFS).
BeeGFS has a second (classified as experimental) client side caching mode called "native", this mode utilized the linux buffer.
I have added support for the BeeGFS  "native" caching mode. (Leaving buffered as the default.). Added a second optional arg.
I have found with certain I/O patterns (MPIIO with small transfer sizes (32k), that native caching is significantly faster than buffered caching mode.
The blue section in the graph below is using buffered cache mode and the red is the I/O performance using "native" caching mode.

Added support for BeeGFS native client cache

---

apps/linpack/build_hpl.sh

created a branch "fix-linkpack-buildhpl" to fix the build script for building hpl in azurehpc apps.
The current script will work only for PBS, but not in SLURM as the DIR variable sets to be "/apps/linpack" in PBS and while running in SLURM it is "/var/spool/slurmd/job00003"
I made the following line
"cp $DIR/Make.Linux_AMD_BLIS ." to "cp $BUILD_DIR/Make.Linux_AMD_BLIS ."
Without this change - Make file will not be copied in SLURM deployment and hpl will not be built.

Modified the correct location of Make.Linux_AMD_BLIS to BUILD_DIR

---

config.json

Correct config.json referenced in the main README file.
Storage options are anf or storageaccount (not azurestorage).

Corrected storage type options referenced in config.json 

---

apps/darshan/fio_darshan.pbs
apps/darshan/install_darshan_runtime.sh
apps/darshan/install_darshan_util.sh
apps/darshan/readme.md

-Added support for non-mpi codes.
-Corrected some errors in darshan-util installation scripts.
-Added non-mpi example PBS script (Generate I/O profile for fio)
-Updated documentation (non-mpi)

Darshan non-mpi support

---

examples/image/pipeline.yml
examples/image/test_matrix.json
examples/nvidia/pipeline.yml
examples/nvidia/test_matrix.json
scripts/create_image.sh

- when capturing an image automatically detect the hyper-v generation so it doesn't need to be specified in the config file
- added multiple tests for building Gen1 and 2 GPU VMs
- added multiple tests for building and capturing Gen1 & Gen2 images

support and test Gen2 images

---

examples/slurm_autoscale/config.json

Just a leftover after a file rename.

Slurm Autoscale - Corrected SKU file name

---

examples/slurm_autoscale/scripts/slurmpartition.sh

Added logic in `slurmpartition.sh` to correctly handle single instance requests or the case in which `instances` in `config.json` is null.
Assigned exact values of memory per CPU as default memory value per partition. This is possible since each partition contains a single VM SKU.

slurmpartition.sh - Improve nodes management

---

examples/beeond/config.json
examples/beeond/pipeline.yml
examples/beeond/test_matrix.json
scripts/setupbeeond.sh

- upgrade to beeond 7.2
- added test matrix on HC, HB, HBv2
- removed PBS from the tests
- fix image version to 7.7.2020062600

Beeond 7.2

---

apps/health_checks/check_clusterkit_results.sh
apps/health_checks/readme.md
apps/health_checks/run_clusterkit.sh

- Added mellanox clusterkit healthchecks (its included in CentOS-HPC marketplace images)
**Example clusterkit healthcheck report**
Examined nodes: hbv2vmss00000a,hbv2vmss00000b,hbv2vmss00000c,hbv2vmss00000d,hbv2vmss00000e,hbv2vmss00000f,hbv2vmss00000h,hbv2vmss00000j,hbv2vmss00000m,hbv2vmss00000n,hbv2vmss00000o,hbv2vmss00000p,hbv2vmss00000r,hbv2vmss00000s,hbv2vmss00000t,hbv2vmss00000u,hbv2vmss00000v,hbv2vmss00000w,hbv2vmss00000x,hbv2vmss00000y,hbv2vmss00000z,hbv2vmss[000000-000002,000004-000009]
===============================
Bandwidth
Minimum bandwidth: 40029 MB/sec hbv2vmss000006, hbv2vmss00000j  (5.0% below the avg)
Maximum bandwidth: 42938 MB/sec hbv2vmss00000e, hbv2vmss00000p
Average bandwidth: 42107 MB/sec
Nodes exhibited poor perforamce with all other nodes:
minimal bandwidth of …

Mellanox Clusterkit

---

pyazhpc/azinstall.py

A marker is created **on each VM** when an install step is completed successfully.  It will only run if the marker is not present.
This has been tested with simple_hpc_pbs and works for scaling up the compute pool (manual steps are required to scale down).
Note: all logs are **appended to**.  This means that the output for previous successful runs will also be shown.  When the marker is detected it is reflected in the output.

Install steps are now idempotent

---

README.md
install.sh
pyazhpc/azhpc.py
pyazhpc/azinstall.py

This was added for my convenience when debugging my scripts for a config.  If an install fails and you would like to make a change to a script and resume this can be used.  E.g. step 15 fails on the install and so you edit your config and run:
azhpc run_install --step 15

Resume install

---

apps/imb-mpi/ringpingpong.sh

On CentOS-HPC:7.7:latest
The following hpcx options gives errors (--map-by core)?   (ringpingpong.sh, with ompi option)
[hcvmss000000:44696] PMIX ERROR: NOT-FOUND in file dstore_base.c at line 2866
[hcvmss000000:44696] PMIX ERROR: NOT-FOUND in file server/pmix_server.c at line 3408
[hcvmss000000:44699] PMIX ERROR: OUT-OF-RESOURCE in file client/pmix_client.c at line 231
[hcvmss000000:44699] OPAL ERROR: Error in file pmix3x_client.c at line 112
*** An error occurred in MPI_Init
*** on a NULL communicator
*** MPI_ERRORS_ARE_FATAL (processes in this communicator will now abort,
***    and potentially your MPI job)

imb-mpi (hpcx options fix)

---

pyazhpc/azinstall.py

Issue where the failure to create a marker is returned as the command exitcode causing azurehpc to fail.

Fix for bug #426

---

scripts/create_image.sh

hyperVGeneration contains now an uppercase G while it was not before
Closing #448

fix breaking change from REST APIs

---

apps/health_checks/allreduce.sh

This script runs an MPI Allreduce microbenchmark on a single node to highlight intra-node latency issues.

Add MPI Allreduce test script to health checks

---

pyazhpc/azinstall.py

fix the breaking change introduced by markers when a script is failing. The error was not bubble up.

bubble up errors

---

experimental/lustre_2.12.6_client_for_centos_hpc_78/build_lustre_2.12.6_client_centOS_hpc_78.sh
experimental/lustre_2.12.6_client_for_centos_hpc_78/readme.md

The official lustre 2.12.6 client will not build on the new CentOS-HPC 7.8 marketplace image (with MOFED 5.2.x)
The script build_lustre_2.12.6_client_centOS_hpc_78.sh can build the Lustre 2.12.6 client on the new CentOS-HPC 7.8 marketplace image.

Build lustre 2.12.6 client on new CentOS-HPC image

---

experimental/lustre_2.12.6_client_for_centos_hpc_78/build_lustre_2.12.6_client_centOS_hpc_78.sh

-Added installation of libyaml-devel

Correct Lustre 2.12.6 client install on CentOS-HPC 7.8

---

examples/simple_hpc_slurm/config.json
examples/simple_hpc_slurm/readme.md
examples/simple_hpc_slurm/scripts/munge.sh
examples/simple_hpc_slurm/scripts/slurmctld.sh
examples/simple_hpc_slurm/scripts/slurmd.sh
examples/simple_hpc_slurm/scripts/slurmnodes.sh
examples/simple_hpc_slurm/scripts/slurmstart.sh

Simple SLURM cluster based on simple_hpc_pbs example. headnode + compute nodes in vmss. Single partition, any VM size should work.
Uses latest SLURM release at the time.

Simple SLURM cluster example

---

experimental/gpu_monitoring/gpu_data_collector.py
experimental/gpu_monitoring/readme.md
experimental/gpu_monitoring/start_gpu_data_collector.sh
experimental/gpu_monitoring/start_gpu_data_collector_cron.sh
experimental/gpu_monitoring/stop_gpu_data_collector.sh
experimental/gpu_monitoring/stop_gpu_data_collector_cron.sh

-Added multiple arguments, to give finer control and flexibility to the GPU Monitor
- Can deploy as stand-alone or via crontab.
./gpu_data_collector.py -h
usage: gpu_data_collector.py [-h] [-dfi DCGM_FIELD_IDS] [-nle NAME_LOG_EVENT]
[-fgm] [-uc] [-tis TIME_INTERVAL_SECONDS]
optional arguments:
-h, --help            show this help message and exit
-dfi DCGM_FIELD_IDS, --dcgm_field_ids DCGM_FIELD_IDS
Select the DCGM field ids you would like to monitor
(if multiple field ids  are desired then separate by commas)
[string] (default: 203,252,1004)
-nle NAME_LOG_EVENT, --name_log_event NAME_LOG_EVENT
Select a name for the log events you want to monitor
(default: MyGPUMonitor)
-fgm, --force_gpu_monitoring
Forces data to be sent to log analytics WS even if no
SLURM job is running on the node …

Update GPU Monitoring scripts

---

experimental/gpu_optimizations/max_gpu_app_clocks.sh
experimental/gpu_optimizations/readme.md

Script to set, reset(-r) or list(-l) the GPU application maximum clock frequencies (memory and graphics).
On NDv4 (A100) it's recommended to always set your GPU's to the maximum application clock frequencies to get the best performance.

GPU optimizations (Set maximum application GPU clock frequencies)

---

experimental/cc_slurm_nhc/cc_slurm_nhc/specs/default/cluster-init/files/configure_nhc.sh
experimental/cc_slurm_nhc/cc_slurm_nhc/specs/default/cluster-init/files/nd96asr_v4.conf
experimental/cc_slurm_nhc/readme.md

-  Changed the dcgmi diag test to be the quick test (-r 1)
-  Reduced the SLURM test interval to be 200 seconds
-  Removed any specific IP addresses and device names from the sample NHC configuration file
-  Some minor modifications to the readme file

cc_nhc slurm update

---

experimental/cc_slurm_nhc/cc_slurm_nhc/specs/default/cluster-init/files/azure_gpu_ecc.nhc
experimental/cc_slurm_nhc/cc_slurm_nhc/specs/default/cluster-init/files/nd96amsr_v4.conf
experimental/cc_slurm_nhc/cc_slurm_nhc/specs/default/cluster-init/files/nd96asr_v4.conf

- Any SRAM ECC error count is an error (>0)
- Increased ECC uncorrectable error count limit to 20000

CC slurm nhc ecc update

---

experimental/cc_slurm_nhc/cc_slurm_nhc/specs/default/cluster-init/files/azure_gpu_clock_throttling.nhc

- Exclude SW Power Cap as a reason to give a warning about GPU throttling.

CC_SLURM_NHC (Exclude reason sw_power_cap from GPU clock throttling warning)

---

experimental/ndv4_a100_healthchecks/run_nccl_all_reduce.sh

- Corrected GPU ID to NUMA mapping on NDv4
- Added argument to check correctness of NCCL all-reduce result.

NDv4 healthchecks (correct GPU ID to NUMA mapping on NDv4)

---

pyazhpc/azinstall.py

ssh_port has no default in azinstall.py which causes the ssh -p option to be set to None (which fails).
If ssh_port is not set then set the default to port 22.

Set default ssh_port to be port 22 (bug fix)

---

README.md
pyazhpc/azinstall.py

- Added support to create a cyclecloud cluster with a customized template file.
If the cyclecloud parameter "template" (in the config.json file) is set to the name of a cyclecloud text template file, it will use that to create the cyclecloud cluster (instead of a built-in cyclecloud template).
"template" : <"Name of the cyclecloud template file">
The format of the template file is <Scheduler_type>_<file_name>.txt
where scheduler can be "pbs" or "slurm". (e.g slurm_ndv4.txt)

Added Support for a customized template file to create a cyclecloud cluster

---

experimental/cc_slurm_nhc/cc_slurm_nhc/specs/default/cluster-init/files/configure_nhc.sh
experimental/cc_slurm_nhc/readme.md

-Use NHC configuration file ND96amsr_v4 (80GB A100), by default.
-Increased time interval between NHC tests.
-Updated readme file

CC_SLURM_NHC (Changed NHC defaults)

---

experimental/cc_slurm_nhc/cc_slurm_nhc/specs/default/cluster-init/files/azure_gpu_app_clocks.nhc

The return statements in the `azure_gpu_app_clocks.nhc` script stop the loop at the first iteration, causing only GPU #0 to have the correct max application frequency to be correct.

Fix NHC GPU application clocks script to iterate across all GPUs

---

experimental/cc_slurm_nhc/cc_slurm_nhc/specs/default/cluster-init/files/azure_cpu_drop_cache_mem.nhc
experimental/cc_slurm_nhc/cc_slurm_nhc/specs/default/cluster-init/files/configure_nhc.sh
experimental/cc_slurm_nhc/cc_slurm_nhc/specs/default/cluster-init/files/hb120-16rs_v3.conf
experimental/cc_slurm_nhc/cc_slurm_nhc/specs/default/cluster-init/files/hb120-32rs_v3.conf
experimental/cc_slurm_nhc/cc_slurm_nhc/specs/default/cluster-init/files/hb120-64rs_v3.conf
experimental/cc_slurm_nhc/cc_slurm_nhc/specs/default/cluster-init/files/hb120-96rs_v3.conf
experimental/cc_slurm_nhc/cc_slurm_nhc/specs/default/cluster-init/files/hb120rs_v3.conf
experimental/cc_slurm_nhc/cc_slurm_nhc/specs/default/cluster-init/files/nd96amsr_v4.conf
experimental/cc_slurm_nhc/cc_slurm_nhc/specs/default/cluster-init/files/nd96asr_v4.conf
experimental/cc_slurm_nhc/readme.md

-Add check to see if CPU cached memory should be dropped. If cached memory is about a set threshold, an
attempt is made to drop the cache to clean up the memory.

CC_SLURM_NHC (Support dropping CPU cached memory.)

---

experimental/cc_slurm_nhc/cc_slurm_nhc/specs/default/cluster-init/files/azure_cuda_bandwidth.nhc
experimental/cc_slurm_nhc/cc_slurm_nhc/specs/default/cluster-init/files/nd96amsr_v4.conf
experimental/cc_slurm_nhc/cc_slurm_nhc/specs/default/cluster-init/files/nd96asr_v4.conf

We found that the CUDA bandwidths might be a little fluttering over time.
A single check_cuda_bw pass might fail and drain the node even if no actual issue is present.
Here the check_cuda_bw test is hardened by allowing multiple passes.
**Parameters:**
The first check_cuda_bw parameter is mandatory and is the bandwidth threshold for test failure.
The second parameter is optional and is the maximum number of iterations. The default is one iteration.
**Success criteria:**
At the first occurrence of a measure bandwidth below the threshold the whole iteration is declared failed and the next iteration is started.
If all iterations fail the check fails.
The check will pass **at the first iteration** where all host-to-device and device-to-host bandwidths are above the threshold.

Iterative check_cuda_bw

---

README.md
pyazhpc/azinstall.py

Add support for running a cyclecloud project script in the background.
New "background" parameter (true or false) (default is false)
"cyclecloud project name": {
{
"script": script_name
"background": true
}
}

Support running cyclecloud project scripts in the background

---

experimental/cc_slurm_nhc/cc_slurm_nhc/specs/default/cluster-init/files/azure_gpu_ecc.nhc
experimental/cc_slurm_nhc/cc_slurm_nhc/specs/default/cluster-init/files/nd96amsr_v4.conf
experimental/cc_slurm_nhc/cc_slurm_nhc/specs/default/cluster-init/files/nd96asr_v4.conf

- Changed the high ECC error count default to be 20M
-  If ECC error count exceeds the count threshold (default 20M), not will be put into a DRAIN state (instead of just issuing a warning)

CC_SLURM_NHC (DRAIN nodes if ECC error count > 20M)

---

experimental/cc_slurm_nhc/cc_slurm_nhc/specs/default/cluster-init/files/build_bandwidthtest.sh
experimental/cc_slurm_nhc/cc_slurm_nhc/specs/default/cluster-init/files/build_perftest_gdr.sh
experimental/cc_slurm_nhc/cc_slurm_nhc/specs/default/cluster-init/files/configure_nhc.sh
experimental/cc_slurm_nhc/cc_slurm_nhc/specs/default/cluster-init/files/install_nhc.sh
experimental/cc_slurm_pyxis_enroot/cc_slurm_pyxis_enroot/specs/default/cluster-init/files/configure_pyxis.sh
experimental/cc_slurm_pyxis_enroot/cc_slurm_pyxis_enroot/specs/default/cluster-init/files/install_enroot.sh
experimental/cc_slurm_pyxis_enroot/cc_slurm_pyxis_enroot/specs/default/cluster-init/files/install_enroot_hooks.sh
experimental/cc_slurm_pyxis_enroot/cc_slurm_pyxis_enroot/specs/default/cluster-init/files/install_pyxis.sh
experimental/cc_slurm_pyxis_enroot/cc_slurm_pyxis_enroot/specs/default/cluster-init/files/slurmd_pmix.sh

Source common_function.sh from CC spec dir.
This prevent errors if the file is not correctly copied where the calling script is located.

Harden scripts sourcing common_function.sh

---

scripts/cyclecli_install.sh

AzureHPC sets `PYTHONPATH=$AZHPC_PYTHONPATH`.
This interferes with the CycleCLI `install.py` when running `cyclecli_install.sh` locally. The result is that required dependencies (e.g. six) are not installed in `$HOME/.cycle/cli/lib64/python3.6/site-packages` as expected by `cyclecloud`.

Fix CycleCLI installation in local host

---

experimental/cc_slurm_nhc/cc_slurm_nhc/specs/default/cluster-init/files/azure_gpu_ecc.nhc
experimental/cc_slurm_nhc/cc_slurm_nhc/specs/default/cluster-init/files/nd96amsr_v4.conf
experimental/cc_slurm_nhc/cc_slurm_nhc/specs/default/cluster-init/files/nd96asr_v4.conf

Modified the GPU ECC error count check, added a SRAM correctable ECC threshold (set to 10k in nhc configuration files).
An SRAM correctable ECC error check will only fail if the count exceeds the threshold (10k).
NHC config file
* || check_gpu_ecc 10000000 **10000**

CC_SLURM_NHC (Added SRAM correctable ECC threshold)

---

experimental/cc_slurm_nhc/cc_slurm_nhc/specs/default/cluster-init/files/azure_nccl_allreduce.nhc

- Added check to NCCL all-reduce test to see if any values are out of bounds

cc_slurm_nhc (Added check for NCCL all-reduce out of bounds error)

---

experimental/deploy_cycle_slurm_ndv4/config.json
experimental/deploy_cycle_slurm_ndv4/config_pyxis_enroot.json
experimental/deploy_cycle_slurm_ndv4/config_pyxis_enroot_sacct.json
experimental/deploy_cycle_slurm_ndv4/scripts/disable_unattended_upgrades.sh

Apply CC project to scheduler and login nodes to disable Ubuntu unattended upgrades.
This functionality is enabled only on base Ubuntu marketplace image. Ubuntu-DSVM already have it disabled.

Disable Ubuntu unattended upgrades

---

experimental/deploy_cycle_slurm_ndv4/config_pyxis_enroot_sacct.json
experimental/deploy_cycle_slurm_ndv4/readme.md
experimental/deploy_cycle_slurm_ndv4/scripts/sunrpc_max_tcp_slot_table_entries.sh
experimental/deploy_cycle_slurm_ndv4/scripts/sunrpc_tcp_max_slot_table_entries.sh

For ANF it is recommended to set the sunrpc kernel parameter tcp_max_slot_table_entries=128, to match a similar parameter on the ANF server. When a client overwhelms the server network stacks ability to process a workload, the server responds by decreasing the window size for the connection (throttling).
Sets the sunrpc kernel parameter tcp_max_slot_table_entries=128

Deploy_cycle_slurm_ndv4(Set sunrpc kernel parameter tcp_max_slot_table_entries=128)

---

README.md
pyazhpc/arm.py
pyazhpc/azhpc.py
pyazhpc/azutil.py

Expose additional peering configuration options to eliminate need to manually configure peering with existing vnets.
- Add config dictionary in ['vnet']['peer'] for gateway options
- Add config fields in ['vnet']['peer'][<peer-name>] for traffic options
- Add method to delete peerings with azhpc-destroy when defined in config.json
- Default configs remain unchanged
- Update to README.md to reflect changes with example of adding peering

Add peering gateway opts

---

pyazhpc/azconfig.py
pyazhpc/azhpc.py
pyazhpc/test/test_azconfig.py
pyazhpc/test/test_config_file.json

Adds the ability to use variables (e.g. "variables.<field>") in config dictionary key names which is useful in avoiding name collisions for resources created in the same account.
As an example, the json blob below is an example where a jumpbox VM is named using the expansion of the variable `variables.jumpbox_name` in the definition of resources.
```
{
"location": "variables.location",
"resource_group": "variables.resource_group",
"install_from": "variables.jumpbox_name",
"admin_user": "variables.admin_user",
"variables": {
"location": "<NOT-SET>",
"resource_group": "<NOT-SET>",
"vnet_resource_group": "variables.resource_group",
"vnet_name": "<NOT-SET>",
"admin_user": "hpcadmin",
"image": "OpenLogic:CentOS:7.7:latest",
"jb_vm_type": "Standard_D8s_v3",
"jumpbox_name": "test-jumpbox"
}, …
```

Add ability to use variables in config dictionary keys

---

experimental/deploy_cycle_slurm_ndv4/prereqs_sacct_la_ws.json

Correct azhpc config variable that defines the mariaDB admin name.

Deploy_cycle_slurm_ndv4 (Corrected mariaDB config variable)

---

experimental/cc_slurm_nhc/cc_slurm_nhc/specs/default/cluster-init/files/configure_nhc.sh
experimental/cc_slurm_nhc/cc_slurm_nhc/specs/default/cluster-init/files/epilog.sh
experimental/cc_slurm_nhc/cc_slurm_nhc/specs/default/cluster-init/files/prolog.sh
experimental/cc_slurm_nhc/cc_slurm_nhc/specs/default/cluster-init/files/wait_for_nhc.sh
experimental/cc_slurm_nhc/readme.md

Added support for autoscaling
-When a node is autoscaled, the prolog.sh waits for NHC to complete instead of killing NHC.
If prolog.sh or eliplog.sh do not exist they are created by configure_nhc.sh 
-remove prolog.sh and elilog.sh scripts.

cc_slurm_nhc (Add autoscaling support)

---

experimental/cc_slurm_nhc/cc_slurm_nhc/specs/default/cluster-init/files/configure_nhc.sh

Create a timestamp in NHC log to identify NHC runs started by epilog

Added timestamp for epilog NHC execution

---

experimental/cc_slurm_nhc/cc_slurm_nhc/specs/default/cluster-init/files/azure_ib_write_bw_gdr.nhc

At times `check_ib_bw_gdr` fails with the following error:
```
Couldn't listen to port 18515
Unable to open file descriptor for socket connection Unable to init the socket connection
Couldn't connect to slurmcluster-hpc-pg0-277:18515
Unable to open file descriptor for socket connection Unable to init the socket connection
```
Adding `netstat` command to provide additional insights on port status.

Added netstat check

---

experimental/cc_slurm_nhc/cc_slurm_nhc/specs/default/cluster-init/files/build_perftest_gdr.sh
experimental/cc_slurm_nhc/cc_slurm_nhc/specs/default/cluster-init/files/nd96amsr_v4.conf
experimental/cc_slurm_nhc/cc_slurm_nhc/specs/default/cluster-init/files/nd96asr_v4.conf

Under Ubuntu-DSVM 20.04 some checks need to be modified in order to correctly pass the tests.
Also the `pciutils-dev` package required by perftest has been renamed to `libpci-dev`.

Modified NDv4/NDmv4 configuration for UbuntuHPC 20.04

---

experimental/cc_slurm_nhc/cc_slurm_nhc/specs/default/cluster-init/files/configure_nhc.sh
experimental/cc_slurm_nhc/cc_slurm_nhc/specs/default/cluster-init/files/nd96amsr_v4.conf
experimental/cc_slurm_nhc/cc_slurm_nhc/specs/default/cluster-init/files/nd96asr_v4.conf

- Create /sched/scripts dir if it does not exist.
- Modified /shared mount check, changed nfs protocol matching pattern to 'nfs*' (will allow nfs3 and nfs4). If default /shared is deployed it uses nfs4 be default.

Cc slurm nhc

---

experimental/cc_slurm_nhc/cc_slurm_nhc/specs/default/cluster-init/files/run_nhc.sh

- Added check in run_nhc.sh epilog script to check if you are on a slurm exclusive node, if on exclusive node run post job nhc, otherwise do not run it.

cc_slurm_nhc (Added check for exclusive node in run_nhc.sh epilog)

---

experimental/cc_slurm_nhc/cc_slurm_nhc/specs/default/cluster-init/files/run_nhc.sh
experimental/cc_slurm_nhc/cc_slurm_nhc/specs/default/cluster-init/files/wait_for_nhc.sh

-Corrected error in pid extraction (while loop was going into an infinite loop, giving a prolog error)
-Corrected error in run_nhc.sh (function exclusive_node)

cc_slurm_nhc (Corrected pid extraction in wait_for_nhc.sh)

---

experimental/cc_slurm_nhc/cc_slurm_nhc/specs/default/cluster-init/files/azure_raid_health.nhc
experimental/cc_slurm_nhc/cc_slurm_nhc/specs/default/cluster-init/files/configure_nhc.sh
experimental/cc_slurm_nhc/cc_slurm_nhc/specs/default/cluster-init/files/nd96amsr_v4.conf
experimental/cc_slurm_nhc/cc_slurm_nhc/specs/default/cluster-init/files/nd96asr_v4.conf

Add test to check RAID array and corresponding file system health.
Performed tests:
1. Check that the file system corresponding to the provided mount point is a RAID device
2. Check that mdadm returns clean array state
3. Check that the array contains the specified number of devices (disks)
4. Check that file can be written at mount point
5. Check that file can be deletes at mount point

Added RAID health check test

---

experimental/cc_slurm_nhc/cc_slurm_nhc/specs/default/cluster-init/files/configure_nhc.sh
experimental/cc_slurm_nhc/cc_slurm_nhc/specs/default/cluster-init/files/wait_for_nhc.sh
experimental/cc_slurm_nhc/readme.md

Fixed bug when NHC is used with autoscaling enabled (i.e AUTOSCALING=1). Added an exit code in the PROLOG, if NHC passed (exit code = 0), if NHC failed (exit code =1).
Added an additional PROLOG option (when AUTOSCALING=1 only). 
if
PROLOG_NOHOLD_REQUEUE=1
and NHC fails (prolog exit code =1), the job will be requeued with no HOLD, i.e. Will attempt to allocate new VM's for the job.
(Default is job will be requeued (with a hold), node will be deallocated (PROLOG_NOHOLD_REQUEUE=0)

Fix Cc slurm nhc autoscaling bug

---

experimental/cc_slurm_nhc/cc_slurm_nhc/specs/default/cluster-init/files/azure_gpu_xid.nhc
experimental/cc_slurm_nhc/cc_slurm_nhc/specs/default/cluster-init/files/nd96amsr_v4.conf
experimental/cc_slurm_nhc/cc_slurm_nhc/specs/default/cluster-init/files/nd96asr_v4.conf

Nvidia driver 510 enables the GPU System Processor (GSP) by default. The GSP allows to offload GPU initialization and management tasks from the CPU improving performance due to lower latency access to GPU hardware internals.
Such driver includes a bug that causes RPCs to GSP to timeout, preventing the correct GPU initialization. This in turn causes NHC GPU tests to hang indefinitely and the node to be drained because of NHC timeout.
To allow a better identification of this error the Xid codes 119 and 120 are added to the `azure_gpu_xid` test.
Also, the test has been moved at the top of the set of GPU tests to identify GPU health issues before any other test requiring GPU initialization are ran.
Finally, a bug in the `azure_gpu_xid` test has been squelched by removing a return statement …

Add Xid code check for RPC from GSP timeout error

---

experimental/check_app_pinning_tool/check_app_pinning.py
experimental/check_app_pinning_tool/readme.md

- Support to use app pinning tool directly in an MPI run script (AZ_MPI_NP and AZ_MPI_ARGS will be defined to access the optimal MPI pinning parameters for openmpi, hpcx, intel MPI and mvapich2).
e.g. On HB120-96rs_v3, run 16 mpi process and 6 threads per process.
export OMP_NUM_THREADS=6
check_app_pinning.py -pps -nv 1 -nppv 16 -ntpp $OMP_NUM_THREADS -mt openmpi
AZ_MPI_NP=$(cat AZ_MPI_NP)
AZ_MPI_ARGS=$(cat AZ_MPI_ARGS)
mpirun  -n $AZ_MPI_NP $AZ_MPI_ARGS <mpi_executable>

App pinning tool (Support using tool directly in mpi run script)

---

experimental/check_app_pinning_tool/check_app_pinning.py
experimental/check_app_pinning_tool/readme.md

- Allow integration of pinning tool with slurm/srun. You can  call app pinning tool in a Slurm script and pass optimal pinning arguments to the srun command.
- Added a new -mt option, "srun"
e.g. Run 16 processes, 6 threads per process on HB120-96rs-v3
#!/bin/bash
#SBATCH --mem=0
#SBATCH --ntasks-per-node=16
#SBATCH --exclusive
module load gcc-9.2.0
module load mpi/hpcx
export OMP_NUM_THREADS=6
export SLURM_CPU_BIND=verbose
**check_app_pinning.py -pps -nv $SLURM_NNODES -nppv $SLURM_NTASKS_PER_NODE -ntpp $OMP_NUM_THREADS -mt srun
AZ_MPI_NP=$(cat AZ_MPI_NP)
AZ_MPI_ARGS=$(cat AZ_MPI_ARGS)**
srun **$AZ_MPI_ARGS** <mpi_executable>
In this case AZ_MPI_ARGS="--mpi=pmix --cpu-bind=mask_cpu:0x3f,0xfc0,0x3f000,0xfc0000,0x3f000000,0xfc0000000,0x3f000000000,0xfc0000000000,0x3f000000000000,0xfc00000000 …

App pinning tool ( slurm/srun integration)

---

experimental/check_app_pinning_tool/check_app_pinning.py

This was happening with intel MPI when mpiexec is also matched.  Example of pinning: 0-3,16-19,32-35,48-51

Fixing case where pinning is a list of ranges

---

experimental/cc_slurm_nhc/cc_slurm_nhc/specs/default/cluster-init/files/azure_nccl_allreduce_ib_loopback.nhc

Bash cannot directly compare float values.
The test was always true, preventing HNC to drain nodes that failed the NCCL loopback test.

NHC - Corrected floats comparison in NCCL loopback test

---

experimental/cc_slurm_pyxis_enroot/cc_slurm_pyxis_enroot/specs/default/cluster-init/files/common_functions.sh
experimental/cc_slurm_pyxis_enroot/cc_slurm_pyxis_enroot/specs/default/cluster-init/files/install_enroot.sh
experimental/cc_slurm_pyxis_enroot/cc_slurm_pyxis_enroot/specs/default/cluster-init/files/install_enroot_hooks.sh

* Add additional logic to install Enroot only on compute nodes when login nodes are present in the cluster
* Lock libnvidia-container to latest version and force installation despite packages version being held in Ubuntu-HPC image

Improve enroot installation 

---

experimental/aks_npd_draino/draino/manifest.yml
experimental/aks_npd_draino/npd/Dockerfile
experimental/aks_npd_draino/npd/Makefile
experimental/aks_npd_draino/npd/deployment/node-problem-detector-config.yaml
experimental/aks_npd_draino/npd/deployment/node-problem-detector.yaml
experimental/aks_npd_draino/readme.md

Reference implementation of how to integrate Azurehpc-health-checks with AKS.
Azurehpc-health-checks are integrated into k8s node problem detector (NPD) and then draino looks for specific GPU failed conditions and cordons/drains nodes.
NPD and Draino modified scripts are provided.

Integrate GPU node health checks into AKS
